/**
 * Celebrity Roast Cards
 *
 * Pre-generated cards for famous celebrities (non-tech) for entertainment.
 * These are fictional roasts for entertainment purposes only.
 */

import { PMElement, PMMove } from "./types";

export interface CelebrityCard {
  id: string;
  name: string;
  title: string;
  company: string;
  imageUrl: string;
  score: number;
  archetypeName: string;
  archetypeEmoji: string;
  archetypeDescription: string;
  element: PMElement;
  moves: PMMove[];
  stage: string;
  weakness: string;
  flavor: string;
  bangerQuote: string;
  naturalRival: string;
  roastBullets: string[];
}

// Helper to determine stage from score
function getStage(score: number): string {
  if (score >= 95) return "Mythical";
  if (score >= 90) return "Legendary";
  if (score >= 80) return "Elite";
  return "Senior";
}

export const CELEBRITY_CARDS: CelebrityCard[] = [
  // === ENTERTAINMENT & COMEDY ===
  {
    id: "john-cena",
    name: "John Cena",
    title: "Wrestler / Actor",
    company: "WWE / Hollywood",
    imageUrl: "/famous/celebrities/generated/john-cena-card.png",
    score: 78,
    archetypeName: "Invisible Stakeholder",
    archetypeEmoji: "👋",
    archetypeDescription: "You can't see his roadmap, but somehow it ships anyway",
    element: "chaos",
    moves: [
      { name: "You Can't See Me", energyCost: 1, damage: 50, effect: "Disappears from Slack for 3 sprints" },
      { name: "Attitude Adjustment", energyCost: 2, damage: 80, effect: "Pivots entire product direction" },
      { name: "Five Knuckle Shuffle", energyCost: 2, damage: 70, effect: "Rapid-fires 5 feature requests" },
    ],
    stage: "Elite",
    weakness: "Visibility",
    flavor: "Has granted more Make-A-Wish requests than PRDs he's written.",
    bangerQuote: "His product strategy is like his entrance music - you feel it before you see it.",
    naturalRival: "Anyone who asks for documentation",
    roastBullets: [
      "Learned Mandarin to expand to Chinese markets, still can't read a sprint burndown",
      "Has 16 world championships but zero completed Jira tickets",
      "The 'never give up' guy who's pivoted careers more times than a failing startup",
      "Somehow both the most visible and invisible person in any room",
    ],
  },
  {
    id: "dwayne-johnson",
    name: "Dwayne Johnson",
    title: "Actor / Entrepreneur",
    company: "Seven Bucks Productions",
    imageUrl: "/famous/celebrities/generated/dwayne-johnson-card.png",
    score: 85,
    archetypeName: "Hustle Culture CEO",
    archetypeEmoji: "💪",
    archetypeDescription: "Wakes up at 4am to post motivational content nobody asked for",
    element: "shipping",
    moves: [
      { name: "People's Elbow Drop", energyCost: 2, damage: 90, effect: "Lands keynote with devastating impact" },
      { name: "Eyebrow Raise", energyCost: 1, damage: 45, effect: "Questions your commitment level" },
      { name: "Teremana Toast", energyCost: 1, damage: 35, effect: "Product placement in every meeting" },
    ],
    stage: "Elite",
    weakness: "Rest Days",
    flavor: "Built a media empire on being likeable. Somehow still exhausting.",
    bangerQuote: "Posts his 4am gym selfies like the rest of us post standup updates.",
    naturalRival: "Anyone who sleeps 8 hours",
    roastBullets: [
      "Has more side hustles than a YC batch combined",
      "The only person who makes selling tequila feel like a TED talk",
      "Every movie is just The Rock playing The Rock in a different costume",
      "LinkedIn influencers study his morning routine like it's scripture",
    ],
  },
  {
    id: "joe-rogan",
    name: "Joe Rogan",
    title: "Podcaster / Commentator",
    company: "JRE Podcast",
    imageUrl: "/famous/celebrities/generated/joe-rogan-card.png",
    score: 72,
    archetypeName: "DMT Product Manager",
    archetypeEmoji: "🎙️",
    archetypeDescription: "Have you ever tried elk meat while reviewing OKRs? Jamie, pull that up",
    element: "chaos",
    moves: [
      { name: "Jamie Pull That", energyCost: 1, damage: 40, effect: "Fact-checks you mid-presentation" },
      { name: "Three Hour Sync", energyCost: 2, damage: 75, effect: "Meeting has no agenda or end time" },
      { name: "Elk Meat Protocol", energyCost: 2, damage: 60, effect: "Biohacks the sprint planning" },
    ],
    stage: "Elite",
    weakness: "Expertise",
    flavor: "Interviews experts and somehow leaves more confused than before.",
    bangerQuote: "Turned 'asking dumb questions confidently' into a $200M Spotify deal.",
    naturalRival: "Fact-checkers",
    roastBullets: [
      "Platforms every opinion equally, especially the unhinged ones",
      "The 'I'm just asking questions' guy with 11 million listeners",
      "Moved to Texas for the freedom to not research anything",
      "His product review process is 'let me try DMT and think about it'",
    ],
  },
  {
    id: "kevin-hart",
    name: "Kevin Hart",
    title: "Comedian / Actor",
    company: "Hartbeat Productions",
    imageUrl: "/famous/celebrities/generated/kevin-hart-card.png",
    score: 76,
    archetypeName: "Vertical Scaler",
    archetypeEmoji: "📏",
    archetypeDescription: "Compensates for lack of height with sheer volume of projects",
    element: "shipping",
    moves: [
      { name: "Short King Energy", energyCost: 1, damage: 55, effect: "Overdelivers to prove doubters wrong" },
      { name: "Loud Standup", energyCost: 2, damage: 70, effect: "Makes same joke 47 times until it lands" },
      { name: "Hustle Grind Repeat", energyCost: 2, damage: 65, effect: "Launches 3 projects simultaneously" },
    ],
    stage: "Elite",
    weakness: "Tall Jokes",
    flavor: "The most successful person who won't stop talking about hard work.",
    bangerQuote: "Has more active projects than AWS services, with similar uptime.",
    naturalRival: "Rollercoaster height requirements",
    roastBullets: [
      "Turned being 5'4\" into a billion dollar personality",
      "Works harder than anyone at telling you how hard he works",
      "Netflix gave him a deal just so he'd stop pitching them",
      "His memoir about struggle was written from his Beverly Hills mansion",
    ],
  },
  {
    id: "ryan-reynolds",
    name: "Ryan Reynolds",
    title: "Actor / Entrepreneur",
    company: "Maximum Effort",
    imageUrl: "/famous/celebrities/generated/ryan-reynolds-card.png",
    score: 88,
    archetypeName: "Deadpool Marketer",
    archetypeEmoji: "🎭",
    archetypeDescription: "Turned self-aware sarcasm into a Fortune 500 marketing strategy",
    element: "politics",
    moves: [
      { name: "Fourth Wall Break", energyCost: 1, damage: 50, effect: "Acknowledges the absurdity publicly" },
      { name: "Aviation Gin Plug", energyCost: 2, damage: 70, effect: "Seamless product placement" },
      { name: "Maximum Effort", energyCost: 2, damage: 85, effect: "Ships viral campaign in 48 hours" },
    ],
    stage: "Elite",
    weakness: "Sincerity",
    flavor: "Made being a sarcastic millennial into a brand empire.",
    bangerQuote: "Sold Mint Mobile by making fun of Mint Mobile. The anti-marketing marketing genius.",
    naturalRival: "Authentic emotional vulnerability",
    roastBullets: [
      "Bought a gin company and a phone company just to make ads",
      "His entire personality is 'what if Deadpool did capitalism'",
      "Made self-deprecation a publicly traded company strategy",
      "Even his apologies have sponsor reads",
    ],
  },
  {
    id: "gordon-ramsay",
    name: "Gordon Ramsay",
    title: "Chef / TV Personality",
    company: "Gordon Ramsay Holdings",
    imageUrl: "/famous/celebrities/generated/gordon-ramsay-card.png",
    score: 82,
    archetypeName: "Code Review Tyrant",
    archetypeEmoji: "👨‍🍳",
    archetypeDescription: "Your PR is RAW. This architecture is DISGUSTING. Get OUT.",
    element: "chaos",
    moves: [
      { name: "It's RAW", energyCost: 1, damage: 60, effect: "Rejects PR with extreme prejudice" },
      { name: "Idiot Sandwich", energyCost: 2, damage: 75, effect: "Humiliates in front of entire team" },
      { name: "Shut It Down", energyCost: 2, damage: 90, effect: "Cancels sprint mid-demo" },
    ],
    stage: "Elite",
    weakness: "Patience",
    flavor: "Michelin stars and emotional damage in equal measure.",
    bangerQuote: "Gives feedback like a code review written in all caps with profanity.",
    naturalRival: "Junior developers with feelings",
    roastBullets: [
      "Built an empire on screaming at people who can't cook",
      "Somehow both terrifying and beloved, like a strict but fair PM",
      "His 'constructive criticism' has caused more tears than onions",
      "Would 100% call your API design a donkey",
    ],
  },
  {
    id: "snoop-dogg",
    name: "Snoop Dogg",
    title: "Rapper / Entrepreneur",
    company: "Death Row Records",
    imageUrl: "/famous/celebrities/generated/snoop-dogg-card.png",
    score: 80,
    archetypeName: "Chill Pivot Master",
    archetypeEmoji: "🌿",
    archetypeDescription: "Has pivoted more times than a startup - cooking shows, football, Martha Stewart",
    element: "vision",
    moves: [
      { name: "Drop It Like It's Hot", energyCost: 2, damage: 75, effect: "Casually drops game-changing feature" },
      { name: "Gin and Juice Review", energyCost: 1, damage: 45, effect: "Provides feedback while vibing" },
      { name: "Olympic Commentary", energyCost: 2, damage: 65, effect: "Narrates any situation perfectly" },
    ],
    stage: "Elite",
    weakness: "Urgency",
    flavor: "The only person who can make a cooking show with Martha Stewart feel on-brand.",
    bangerQuote: "Career pivots hit different when you're high on life (and other things).",
    naturalRival: "Drug tests",
    roastBullets: [
      "Went from gangsta rap to cooking with Martha Stewart. Legend.",
      "Olympic commentator energy is what every standup needs",
      "Has reinvented himself more times than Madonna",
      "The 'I'm too chill to fail' business strategy actually works for him",
    ],
  },
  {
    id: "kim-kardashian",
    name: "Kim Kardashian",
    title: "Media Personality / Entrepreneur",
    company: "SKIMS / KKW",
    imageUrl: "/famous/celebrities/generated/kim-kardashian-card.png",
    score: 79,
    archetypeName: "Influencer PM",
    archetypeEmoji: "📸",
    archetypeDescription: "Turned a scandal into a billion-dollar empire through pure shamelessness",
    element: "politics",
    moves: [
      { name: "Break The Internet", energyCost: 2, damage: 85, effect: "Goes viral, crashes competitors" },
      { name: "Contour Strategy", energyCost: 1, damage: 50, effect: "Makes any product look flawless" },
      { name: "Momager Call", energyCost: 2, damage: 70, effect: "Deploys Kris Jenner for negotiations" },
    ],
    stage: "Elite",
    weakness: "Privacy",
    flavor: "Studied law while running a shapewear empire. Multitasking queen.",
    bangerQuote: "Built an empire on oversharing, which is basically content marketing.",
    naturalRival: "Anyone who values privacy",
    roastBullets: [
      "Turned 'famous for being famous' into a legitimate business model",
      "SKIMS is worth billions because she understood product-market fit",
      "Now studying law, proving literally anyone can pivot",
      "The OG influencer before influencer was even a word",
    ],
  },
  {
    id: "kanye-west",
    name: "Kanye West",
    title: "Artist / Designer",
    company: "Yeezy",
    imageUrl: "/famous/celebrities/generated/kanye-west-card.png",
    score: 84,
    archetypeName: "Visionary Chaos Agent",
    archetypeEmoji: "🎨",
    archetypeDescription: "Genius-level creativity meets zero impulse control on social media",
    element: "chaos",
    moves: [
      { name: "Imma Let You Finish", energyCost: 1, damage: 55, effect: "Interrupts every meeting" },
      { name: "Yeezy Season", energyCost: 2, damage: 80, effect: "Drops product nobody expected" },
      { name: "Twitter Meltdown", energyCost: 2, damage: 95, effect: "Tanks own stock price instantly" },
    ],
    stage: "Elite",
    weakness: "Silence",
    flavor: "The gap between his genius and his tweets is a clinical study.",
    bangerQuote: "Sold $2B worth of ugly shoes. The 'I told you so' energy is eternal.",
    naturalRival: "His own Twitter account",
    roastBullets: [
      "Made ugly shoes worth thousands through sheer audacity",
      "Every public appearance is either iconic or a disaster",
      "The 'misunderstood genius' who keeps explaining himself poorly",
      "Would interrupt a board meeting to announce he's running for president",
    ],
  },
  {
    id: "oprah-winfrey",
    name: "Oprah Winfrey",
    title: "Media Mogul",
    company: "Harpo Productions / OWN",
    imageUrl: "/famous/celebrities/generated/oprah-winfrey-card.png",
    score: 95,
    archetypeName: "Enterprise Empath",
    archetypeEmoji: "✨",
    archetypeDescription: "Turned emotional intelligence into a multimedia empire",
    element: "vision",
    moves: [
      { name: "You Get A Feature", energyCost: 2, damage: 85, effect: "Ships to everyone simultaneously" },
      { name: "Book Club Bump", energyCost: 1, damage: 60, effect: "Endorsement creates instant success" },
      { name: "Aha Moment", energyCost: 2, damage: 75, effect: "Sudden insight solves everything" },
    ],
    stage: "Mythical",
    weakness: "Bread",
    flavor: "Made billions by asking people about their feelings. Validation economy pioneer.",
    bangerQuote: "The only person whose book recommendation is worth more than a VC check.",
    naturalRival: "Carbohydrates",
    roastBullets: [
      "Her endorsement is worth more than Series A funding",
      "Made Dr. Phil and Dr. Oz famous, which is... a choice",
      "The Weight Watchers investment while loving bread is peak relatability",
      "Built an empire on 'you get a car' energy",
    ],
  },
  {
    id: "lebron-james",
    name: "LeBron James",
    title: "NBA Player / Entrepreneur",
    company: "SpringHill Company",
    imageUrl: "/famous/celebrities/generated/lebron-james-card.png",
    score: 91,
    archetypeName: "GOAT Debater",
    archetypeEmoji: "🏀",
    archetypeDescription: "Optimizes everything including the conversation about his legacy",
    element: "strategy",
    moves: [
      { name: "The Decision", energyCost: 2, damage: 80, effect: "Announces pivot in worst way possible" },
      { name: "LeGM Mode", energyCost: 2, damage: 75, effect: "Trades teammates for better ones" },
      { name: "Taco Tuesday", energyCost: 1, damage: 40, effect: "Attempts to trademark basic phrase" },
    ],
    stage: "Legendary",
    weakness: "Humility",
    flavor: "Has more championships than PR disasters, but it's close.",
    bangerQuote: "Calls himself the King and has the receipts to back it up. Mostly.",
    naturalRival: "Michael Jordan comparisons",
    roastBullets: [
      "The Decision was the worst product launch in sports history",
      "Trying to trademark 'Taco Tuesday' is peak billionaire brain",
      "Plays GM, coach, and player - the ultimate scope creep",
      "Space Jam 2 was his pivot to content that nobody asked for",
    ],
  },
  {
    id: "taylor-swift",
    name: "Taylor Swift",
    title: "Artist / Songwriter",
    company: "Taylor Swift Productions",
    imageUrl: "/famous/celebrities/generated/taylor-swift-card.png",
    score: 93,
    archetypeName: "Version Control Queen",
    archetypeEmoji: "👑",
    archetypeDescription: "Re-released her entire product catalog to own her masters. Petty legend.",
    element: "strategy",
    moves: [
      { name: "Taylor's Version", energyCost: 2, damage: 90, effect: "Forks and replaces original product" },
      { name: "Easter Egg Drop", energyCost: 1, damage: 55, effect: "Fans decode hidden roadmap" },
      { name: "Squad Goals", energyCost: 2, damage: 70, effect: "Assembles all-star collaboration" },
    ],
    stage: "Legendary",
    weakness: "Criticism",
    flavor: "Weaponized the breakup into a billion-dollar industry.",
    bangerQuote: "Re-recorded her entire catalog out of spite. The ultimate legacy migration.",
    naturalRival: "Scooter Braun",
    roastBullets: [
      "Turned 'I own my work' into the greatest revenge arc in music",
      "Her fans decode Easter eggs like they're solving ARGs",
      "Every ex-boyfriend is basically free content",
      "The Eras Tour grossed more than most countries' GDP",
    ],
  },
  {
    id: "mrbeast",
    name: "MrBeast",
    title: "YouTuber / Philanthropist",
    company: "MrBeast",
    imageUrl: "/famous/celebrities/generated/mrbeast-card.png",
    score: 89,
    archetypeName: "Viral Growth Hacker",
    archetypeEmoji: "💰",
    archetypeDescription: "Cracked the YouTube algorithm by giving away everything",
    element: "data",
    moves: [
      { name: "Squid Game IRL", energyCost: 2, damage: 85, effect: "Recreates expensive IP for content" },
      { name: "Cash Cannon", energyCost: 2, damage: 80, effect: "Throws money at engagement" },
      { name: "Thumbnail A/B Test", energyCost: 1, damage: 50, effect: "Optimizes click-through rate" },
    ],
    stage: "Elite",
    weakness: "Small Budgets",
    flavor: "Proved you can buy engagement if you're creative about it.",
    bangerQuote: "Treats YouTube like a startup with 'spend money to make money' energy.",
    naturalRival: "Modest production budgets",
    roastBullets: [
      "Spends millions on videos to make millions on videos. Math checks out.",
      "Built Feastables because chocolate bars needed more content marketing",
      "His philanthropy is also content, which is either genius or dystopian",
      "Makes other YouTubers look like they're not even trying",
    ],
  },
  {
    id: "drake",
    name: "Drake",
    title: "Rapper / Actor",
    company: "OVO",
    imageUrl: "/famous/celebrities/generated/drake-card.png",
    score: 77,
    archetypeName: "Soft Launch Specialist",
    archetypeEmoji: "🦉",
    archetypeDescription: "Started from Degrassi, now he's here. Still in his feelings.",
    element: "politics",
    moves: [
      { name: "Soft Launch", energyCost: 1, damage: 45, effect: "Teases feature without committing" },
      { name: "Certified Lover Boy", energyCost: 2, damage: 70, effect: "Overpromises, underwhelms" },
      { name: "Ghostwriter Collab", energyCost: 2, damage: 80, effect: "Ships with external help" },
    ],
    stage: "Elite",
    weakness: "Authenticity",
    flavor: "Made being emotional and soft into hard rapper cred somehow.",
    bangerQuote: "Started from the bottom (of a Canadian sitcom) now we're here.",
    naturalRival: "Kendrick Lamar",
    roastBullets: [
      "The 'I miss you' texts of hip hop",
      "Has more ghostwriting allegations than shipped albums",
      "Beefing with everyone is basically his marketing strategy",
      "From wheelchair Jimmy to rap mogul is actually impressive pivot",
    ],
  },
  {
    id: "guy-fieri",
    name: "Guy Fieri",
    title: "Chef / TV Host",
    company: "Flavortown",
    imageUrl: "/famous/celebrities/generated/guy-fieri-card.png",
    score: 74,
    archetypeName: "Flavortown Mayor",
    archetypeEmoji: "🔥",
    archetypeDescription: "Taking you to Flavortown, which is apparently a real business strategy",
    element: "shipping",
    moves: [
      { name: "Diners Drive-Ins", energyCost: 2, damage: 70, effect: "Features every small business" },
      { name: "Donkey Sauce", energyCost: 1, damage: 45, effect: "Adds proprietary sauce to everything" },
      { name: "Out of Bounds", energyCost: 2, damage: 65, effect: "Takes bite with sunglasses on backwards" },
    ],
    stage: "Elite",
    weakness: "Fine Dining",
    flavor: "The frosted tips that launched a thousand food tours.",
    bangerQuote: "Made frosted tips and flame shirts into a legitimate media empire.",
    naturalRival: "Food critics",
    roastBullets: [
      "Somehow the most hated and most loved food personality",
      "Officiated 101 gay weddings. Actually wholesome.",
      "Flavortown has no zoning laws and we respect that",
      "The backwards sunglasses are structural at this point",
    ],
  },
  {
    id: "conor-mcgregor",
    name: "Conor McGregor",
    title: "Fighter / Entrepreneur",
    company: "Proper No. Twelve",
    imageUrl: "/famous/celebrities/generated/conor-mcgregor-card.png",
    score: 73,
    archetypeName: "Trash Talk PM",
    archetypeEmoji: "🥊",
    archetypeDescription: "Talks more trash than he ships features, but the hype machine works",
    element: "chaos",
    moves: [
      { name: "Press Conference", energyCost: 1, damage: 60, effect: "Generates buzz through chaos" },
      { name: "Proper Twelve Plug", energyCost: 1, damage: 35, effect: "Sells whiskey mid-fight" },
      { name: "Left Hand Shot", energyCost: 2, damage: 95, effect: "One hit wonder, literally" },
    ],
    stage: "Elite",
    weakness: "Ground Game",
    flavor: "Sold more whiskey than fights won in the past 5 years.",
    bangerQuote: "The trash talk writes checks that his recent fight record can't cash.",
    naturalRival: "Khabib Nurmagomedov",
    roastBullets: [
      "Made more money promoting whiskey than actually fighting",
      "The 'who da fook is that guy' energy is his entire brand",
      "Peaked at 'We're not here to take part, we're here to take over'",
      "His Twitter feuds hit harder than his recent fights",
    ],
  },
  {
    id: "will-smith",
    name: "Will Smith",
    title: "Actor / Producer",
    company: "Westbrook Studios",
    imageUrl: "/famous/celebrities/generated/will-smith-card.png",
    score: 71,
    archetypeName: "Reputation Crasher",
    archetypeEmoji: "👋",
    archetypeDescription: "Thirty years of brand building demolished in 3 seconds on live TV",
    element: "chaos",
    moves: [
      { name: "Keep My Name", energyCost: 2, damage: 90, effect: "Escalates conflict dramatically" },
      { name: "Fresh Prince Charm", energyCost: 1, damage: 45, effect: "Reverts to beloved persona" },
      { name: "YouTube Rewind", energyCost: 2, damage: 50, effect: "Joins trending disasters" },
    ],
    stage: "Elite",
    weakness: "Impulse Control",
    flavor: "The slap heard 'round the world. Crisis management nightmare.",
    bangerQuote: "Built the perfect Hollywood brand, then Ctrl+Z'd it live at the Oscars.",
    naturalRival: "Chris Rock",
    roastBullets: [
      "Went from America's dad to PR case study in one swing",
      "The Oscar speech after the slap was peak cognitive dissonance",
      "YouTube Rewind cameo was somehow his second worst decision",
      "Wrote a book about self-improvement before the incident. Ironic.",
    ],
  },
  {
    id: "shaquille-oneal",
    name: "Shaquille O'Neal",
    title: "NBA Legend / Entrepreneur",
    company: "Multiple Investments",
    imageUrl: "/famous/celebrities/generated/shaquille-oneal-card.png",
    score: 83,
    archetypeName: "Portfolio Dunker",
    archetypeEmoji: "🏀",
    archetypeDescription: "Invested in everything from Papa John's to The General. Diversification king.",
    element: "politics",
    moves: [
      { name: "Shaq Attack", energyCost: 2, damage: 85, effect: "Dominates any market he enters" },
      { name: "Free Throw Miss", energyCost: 1, damage: 30, effect: "Execution has gaps" },
      { name: "Inside the NBA", energyCost: 2, damage: 70, effect: "Roasts Charles Barkley" },
    ],
    stage: "Elite",
    weakness: "Free Throws",
    flavor: "Owns more franchises than championship rings, which is saying something.",
    bangerQuote: "Turned 'I'm big and funny' into one of the most diverse portfolios in sports.",
    naturalRival: "Free throw lines",
    roastBullets: [
      "Makes more from The General ads than most people's salaries",
      "His beef with Kobe was the original founder conflict",
      "Inside the NBA is basically a podcast that pays millions",
      "Somehow makes Icy Hot commercials feel natural",
    ],
  },
  {
    id: "martha-stewart",
    name: "Martha Stewart",
    title: "Business Mogul",
    company: "Martha Stewart Living",
    imageUrl: "/famous/celebrities/generated/martha-stewart-card.png",
    score: 86,
    archetypeName: "Comeback Homemaker",
    archetypeEmoji: "🏡",
    archetypeDescription: "Went to prison, came out with better content. Rehabilitation queen.",
    element: "strategy",
    moves: [
      { name: "Lifestyle Brand", energyCost: 2, damage: 75, effect: "Monetizes literally everything" },
      { name: "Prison Pivot", energyCost: 2, damage: 80, effect: "Turns setback into content" },
      { name: "Snoop Collab", energyCost: 1, damage: 55, effect: "Unexpected partnership success" },
    ],
    stage: "Elite",
    weakness: "SEC",
    flavor: "Made going to prison a brand-building opportunity.",
    bangerQuote: "Federal prison was just an unplanned sabbatical for brand reinvention.",
    naturalRival: "Insider trading regulations",
    roastBullets: [
      "Turned felony conviction into a career boost somehow",
      "The Snoop Dogg friendship is the crossover nobody expected",
      "Makes homemaking feel aspirational and unattainable",
      "Thirst traps at 83 proving age is just a number",
    ],
  },
  {
    id: "arnold-schwarzenegger",
    name: "Arnold Schwarzenegger",
    title: "Actor / Politician",
    company: "Formerly California",
    imageUrl: "/famous/celebrities/generated/arnold-schwarzenegger-card.png",
    score: 90,
    archetypeName: "Terminator Pivot",
    archetypeEmoji: "💪",
    archetypeDescription: "Bodybuilder to actor to governor. The ultimate career speedrun.",
    element: "shipping",
    moves: [
      { name: "I'll Be Back", energyCost: 1, damage: 55, effect: "Always returns from setbacks" },
      { name: "Governator Mode", energyCost: 2, damage: 80, effect: "Pivots entire career trajectory" },
      { name: "Get To Da Choppa", energyCost: 2, damage: 70, effect: "Evacuates failing projects" },
    ],
    stage: "Legendary",
    weakness: "Pronunciation",
    flavor: "Proof that you can be terrible at English and still run California.",
    bangerQuote: "Speedran careers: Mr. Universe to Terminator to Governor. Any questions?",
    naturalRival: "The letter 'R'",
    roastBullets: [
      "Became governor with less English fluency than some immigrants",
      "The accent became a feature, not a bug",
      "Still making fitness content in his 70s. Respect.",
      "Went from 'crush your enemies' to 'crush climate change'",
    ],
  },
  {
    id: "tom-brady",
    name: "Tom Brady",
    title: "NFL Legend",
    company: "TB12 / Autograph",
    imageUrl: "/famous/celebrities/generated/tom-brady-card.png",
    score: 92,
    archetypeName: "GOAT Optimizer",
    archetypeEmoji: "🏈",
    archetypeDescription: "Optimized diet, sleep, and performance. Still can't retire properly.",
    element: "data",
    moves: [
      { name: "Avocado Protocol", energyCost: 1, damage: 50, effect: "Extreme diet optimization" },
      { name: "TB12 Method", energyCost: 2, damage: 75, effect: "Sells you his system" },
      { name: "Un-Retirement", energyCost: 2, damage: 85, effect: "Comes back after leaving" },
    ],
    stage: "Legendary",
    weakness: "Retirement",
    flavor: "So optimized he forgot how to quit.",
    bangerQuote: "Seven Super Bowls and still doesn't know how to stay retired.",
    naturalRival: "Father Time (sort of)",
    roastBullets: [
      "Retired twice because once wasn't dramatic enough",
      "The TB12 diet bans tomatoes. Red flag.",
      "Left his family for football, then left football, then left retirement",
      "Makes other QBs look like they're not even trying",
    ],
  },
  {
    id: "beyonce",
    name: "Beyoncé",
    title: "Artist / Entrepreneur",
    company: "Parkwood Entertainment",
    imageUrl: "/famous/celebrities/generated/beyonce-card.png",
    score: 96,
    archetypeName: "Queen Bee PM",
    archetypeEmoji: "🐝",
    archetypeDescription: "Drops albums with zero marketing. The anti-roadmap approach.",
    element: "vision",
    moves: [
      { name: "Surprise Drop", energyCost: 2, damage: 95, effect: "Releases product with no warning" },
      { name: "Beyhive Swarm", energyCost: 2, damage: 85, effect: "Activates army of defenders" },
      { name: "Visual Album", energyCost: 2, damage: 80, effect: "Redefines entire format" },
    ],
    stage: "Mythical",
    weakness: "Interviews",
    flavor: "Hasn't done a real interview in years. The mystery is the brand.",
    bangerQuote: "Invented the surprise album drop. Everyone else is just catching up.",
    naturalRival: "Traditional marketing",
    roastBullets: [
      "Doesn't promote albums, just drops them and watches the world react",
      "The Beyhive will defend her honor with their lives",
      "Made country music in 2024 because she felt like it",
      "So private we barely know she exists, yet she's everywhere",
    ],
  },
  {
    id: "post-malone",
    name: "Post Malone",
    title: "Rapper / Singer",
    company: "Republic Records",
    imageUrl: "/famous/celebrities/generated/post-malone-card.png",
    score: 75,
    archetypeName: "Face Tattoo CEO",
    archetypeEmoji: "🎸",
    archetypeDescription: "Looks like he lives in a gas station bathroom but makes hits",
    element: "chaos",
    moves: [
      { name: "Bud Light Seltzer", energyCost: 1, damage: 40, effect: "Sponsor integration complete" },
      { name: "Sad Boy Anthem", energyCost: 2, damage: 70, effect: "Makes everyone feel things" },
      { name: "Genre Pivot", energyCost: 2, damage: 65, effect: "Switches genres effortlessly" },
    ],
    stage: "Elite",
    weakness: "Skincare",
    flavor: "The disconnect between his appearance and his net worth is art.",
    bangerQuote: "Looks like he'd ask you for bus fare, actually worth $45 million.",
    naturalRival: "Dermatologists",
    roastBullets: [
      "Face tattoos say 'I've given up' but bank account says otherwise",
      "Made sad music for people who pregame at Applebee's",
      "Somehow pivoted to country and it worked",
      "The most successful person who looks like they shouldn't be",
    ],
  },
  {
    id: "dj-khaled",
    name: "DJ Khaled",
    title: "DJ / Producer",
    company: "We The Best Music",
    imageUrl: "/famous/celebrities/generated/dj-khaled-card.png",
    score: 70,
    archetypeName: "Hype Man PM",
    archetypeEmoji: "🔑",
    archetypeDescription: "Yells his own name on other people's songs. That's the whole product.",
    element: "politics",
    moves: [
      { name: "Another One", energyCost: 1, damage: 40, effect: "Requests additional features" },
      { name: "Major Key", energyCost: 1, damage: 45, effect: "Shares obvious wisdom" },
      { name: "We The Best", energyCost: 2, damage: 60, effect: "Self-affirmation marketing" },
    ],
    stage: "Elite",
    weakness: "Losing",
    flavor: "Built a career on yelling his name and 'another one'. Respect.",
    bangerQuote: "Gets producer credit for yelling 'DJ Khaled' over other people's work.",
    naturalRival: "L's",
    roastBullets: [
      "The most successful person whose job is unclear",
      "Snapchat made him a mogul through pure unhinged energy",
      "Won't eat his wife out but will eat success for breakfast",
      "Every song is just him introducing better artists",
    ],
  },
  {
    id: "ellen-degeneres",
    name: "Ellen DeGeneres",
    title: "TV Host / Comedian",
    company: "A Very Good Production",
    imageUrl: "/famous/celebrities/generated/ellen-degeneres-card.png",
    score: 65,
    archetypeName: "Nice Brand Crisis",
    archetypeEmoji: "💃",
    archetypeDescription: "Built 'be kind' brand, turns out the workplace was not kind",
    element: "politics",
    moves: [
      { name: "Dance Break", energyCost: 1, damage: 40, effect: "Distracts from workplace issues" },
      { name: "Be Kind", energyCost: 2, damage: 50, effect: "Brand message meets reality" },
      { name: "Celeb Scare", energyCost: 1, damage: 35, effect: "Pranks A-listers for content" },
    ],
    stage: "Senior",
    weakness: "Glassdoor",
    flavor: "The 'be kind' queen whose employees had a different experience.",
    bangerQuote: "Pioneered daytime niceness until the workplace reviews came out.",
    naturalRival: "Former employees",
    roastBullets: [
      "The gap between 'be kind' and employee reviews is a canyon",
      "Twenty years of dancing couldn't dance away the scandal",
      "Finding Dory voice actress with finding kindness issues",
      "Retired to avoid more accountability. Strategic exit.",
    ],
  },
  {
    id: "conan-obrien",
    name: "Conan O'Brien",
    title: "Comedian / Podcaster",
    company: "Team Coco",
    imageUrl: "/famous/celebrities/generated/conan-obrien-card.png",
    score: 84,
    archetypeName: "Late Night Pivot",
    archetypeEmoji: "🧡",
    archetypeDescription: "Got screwed by NBC, somehow became more beloved. Chaos survivor.",
    element: "vision",
    moves: [
      { name: "Self-Deprecate", energyCost: 1, damage: 50, effect: "Turns L's into content" },
      { name: "Podcast Pivot", energyCost: 2, damage: 75, effect: "Adapts to new medium perfectly" },
      { name: "Travel Chaos", energyCost: 2, damage: 70, effect: "Creates content anywhere" },
    ],
    stage: "Elite",
    weakness: "Sunlight",
    flavor: "The Tonight Show disaster made him cooler somehow.",
    bangerQuote: "NBC tried to bury him and he just got funnier underground.",
    naturalRival: "Jay Leno's legacy",
    roastBullets: [
      "Got pushed out of Tonight Show, became a podcasting legend",
      "The palest man in entertainment. Literally glows.",
      "His travel specials are just him being confused internationally",
      "Self-awareness as a superpower, wielded ruthlessly",
    ],
  },
  {
    id: "steve-harvey",
    name: "Steve Harvey",
    title: "TV Host / Comedian",
    company: "Steve Harvey Media",
    imageUrl: "/famous/celebrities/generated/steve-harvey-card.png",
    score: 72,
    archetypeName: "Reaction Meme King",
    archetypeEmoji: "😐",
    archetypeDescription: "His confused face is more famous than most people's careers",
    element: "chaos",
    moves: [
      { name: "Survey Says", energyCost: 1, damage: 45, effect: "Validates with audience data" },
      { name: "Wrong Winner", energyCost: 2, damage: 80, effect: "Catastrophic announcement error" },
      { name: "Moral Lecture", energyCost: 2, damage: 55, effect: "Unsolicited life advice" },
    ],
    stage: "Elite",
    weakness: "Envelopes",
    flavor: "The Miss Universe incident was peak chaos content.",
    bangerQuote: "Made one mistake live on TV and it became more iconic than the actual winner.",
    naturalRival: "Award envelopes",
    roastBullets: [
      "The Miss Universe mistake was the best thing that ever happened to him",
      "Gives relationship advice despite multiple divorces",
      "Family Feud reactions alone are a content empire",
      "The suit game is immaculate though",
    ],
  },
  {
    id: "jimmy-fallon",
    name: "Jimmy Fallon",
    title: "TV Host",
    company: "NBC / Tonight Show",
    imageUrl: "/famous/celebrities/generated/jimmy-fallon-card.png",
    score: 68,
    archetypeName: "Slap Desk Laugher",
    archetypeEmoji: "😂",
    archetypeDescription: "Laughs at everything. Everything. Even when it's not funny.",
    element: "politics",
    moves: [
      { name: "Desk Slap", energyCost: 1, damage: 35, effect: "Oversells every joke" },
      { name: "Celebrity Games", energyCost: 2, damage: 60, effect: "Makes stars play silly games" },
      { name: "Break Character", energyCost: 1, damage: 40, effect: "Can't keep it together" },
    ],
    stage: "Senior",
    weakness: "Subtlety",
    flavor: "Breaking on SNL was endearing. Doing it for 20 years is concerning.",
    bangerQuote: "The most enthusiastic person about things that aren't that funny.",
    naturalRival: "Genuine reactions",
    roastBullets: [
      "Would laugh at a funeral if someone told a bad pun",
      "Slapped his desk so many times it needs therapy",
      "The Trump hair tousle was... a choice",
      "Every interview feels like he's meeting his hero, every time",
    ],
  },
  {
    id: "serena-williams",
    name: "Serena Williams",
    title: "Tennis Legend / Investor",
    company: "Serena Ventures",
    imageUrl: "/famous/celebrities/generated/serena-williams-card.png",
    score: 94,
    archetypeName: "GOAT Investor",
    archetypeEmoji: "🎾",
    archetypeDescription: "Dominated tennis, now dominating VC. Can't stop winning.",
    element: "strategy",
    moves: [
      { name: "Grand Slam", energyCost: 2, damage: 95, effect: "Wins repeatedly at everything" },
      { name: "Serena Ventures", energyCost: 2, damage: 80, effect: "Portfolio outperforms market" },
      { name: "Mom Mode", energyCost: 1, damage: 55, effect: "Balances everything somehow" },
    ],
    stage: "Legendary",
    weakness: "Retirement",
    flavor: "23 Grand Slams weren't enough, now conquering venture capital.",
    bangerQuote: "Tennis was just the tutorial. VC is the main game now.",
    naturalRival: "Doubters (all defeated)",
    roastBullets: [
      "Turned athletic dominance into investment dominance",
      "Her VC fund has better returns than most tech bros",
      "Retired from tennis to focus on building her empire",
      "Makes motherhood and world domination look easy",
    ],
  },
  {
    id: "bad-bunny",
    name: "Bad Bunny",
    title: "Artist / Actor",
    company: "Rimas Entertainment",
    imageUrl: "/famous/celebrities/generated/bad-bunny-card.png",
    score: 85,
    archetypeName: "Reggaeton Renegade",
    archetypeEmoji: "🐰",
    archetypeDescription: "Made reggaeton global while wearing nail polish. Breaking norms profitably.",
    element: "vision",
    moves: [
      { name: "Un Verano Sin Ti", energyCost: 2, damage: 85, effect: "Drops album of the summer" },
      { name: "Phone Smash", energyCost: 1, damage: 50, effect: "Destroys fan's phone, goes viral" },
      { name: "WWE Cameo", energyCost: 2, damage: 65, effect: "Unexpected crossover appearance" },
    ],
    stage: "Elite",
    weakness: "Paparazzi",
    flavor: "Most streamed artist while barely speaking English in interviews.",
    bangerQuote: "Took over global music without compromising his Spanish-language roots.",
    naturalRival: "Intrusive fans",
    roastBullets: [
      "Made the whole world learn Spanish just to sing along",
      "Threw a fan's phone in the ocean. Based.",
      "Gender norms mean nothing when you're that talented",
      "WWE appearance was somehow the least weird thing he's done",
    ],
  },
  {
    id: "billie-eilish",
    name: "Billie Eilish",
    title: "Artist",
    company: "Darkroom / Interscope",
    imageUrl: "/famous/celebrities/generated/billie-eilish-card.png",
    score: 83,
    archetypeName: "Whisper Pop CEO",
    archetypeEmoji: "🖤",
    archetypeDescription: "Made mumbling into a microphone with your brother into Grammy wins",
    element: "vision",
    moves: [
      { name: "ASMR Vocals", energyCost: 1, damage: 50, effect: "Whispers hit different" },
      { name: "Bad Guy Energy", energyCost: 2, damage: 75, effect: "Redefines pop music" },
      { name: "Baggy Clothes", energyCost: 1, damage: 45, effect: "Fashion as statement" },
    ],
    stage: "Elite",
    weakness: "Volume",
    flavor: "Proof that a bedroom, your brother, and depression can win Grammys.",
    bangerQuote: "Made an entire generation whisper-sing in their bedrooms for content.",
    naturalRival: "Traditional pop production",
    roastBullets: [
      "Recorded in a bedroom and swept the Grammys at 17",
      "The baggy clothes era was a whole movement",
      "Brother Finneas does half the work, gets half the credit",
      "Made being sad a whole aesthetic and business model",
    ],
  },
  {
    id: "lizzo",
    name: "Lizzo",
    title: "Artist / Flutist",
    company: "Atlantic Records",
    imageUrl: "/famous/celebrities/generated/lizzo-card.png",
    score: 76,
    archetypeName: "Self-Love Brand",
    archetypeEmoji: "💖",
    archetypeDescription: "Turned body positivity into platinum records and controversy",
    element: "chaos",
    moves: [
      { name: "100% That B", energyCost: 2, damage: 70, effect: "Maximum confidence energy" },
      { name: "Flute Solo", energyCost: 1, damage: 50, effect: "Classical training flex" },
      { name: "Twerk Break", energyCost: 2, damage: 65, effect: "Disrupts expectations" },
    ],
    stage: "Elite",
    weakness: "Lawsuits",
    flavor: "From flute playing to Grammys to workplace allegations. A journey.",
    bangerQuote: "Made self-love a brand, then the employee lawsuits dropped.",
    naturalRival: "Former dancers",
    roastBullets: [
      "Classically trained flutist to pop star is an elite pivot",
      "The body positivity message hit until the lawsuits didn't match",
      "Played James Madison's crystal flute like it was normal",
      "Truth Hurts indeed when employees start talking",
    ],
  },
  {
    id: "logan-paul",
    name: "Logan Paul",
    title: "YouTuber / Wrestler",
    company: "Prime / WWE",
    imageUrl: "/famous/celebrities/generated/logan-paul-card.png",
    score: 67,
    archetypeName: "Controversy Cockroach",
    archetypeEmoji: "🥊",
    archetypeDescription: "Survived career-ending scandal, now sells energy drinks. Unkillable.",
    element: "chaos",
    moves: [
      { name: "Prime Time", energyCost: 2, damage: 70, effect: "Launches viral beverage" },
      { name: "WWE Stunner", energyCost: 2, damage: 75, effect: "Surprisingly athletic" },
      { name: "Redemption Arc", energyCost: 1, damage: 50, effect: "Rehabilitates image" },
    ],
    stage: "Senior",
    weakness: "Forests",
    flavor: "The forest incident should have ended him. Prime is everywhere now.",
    bangerQuote: "Career died in a Japanese forest, resurrected through energy drinks.",
    naturalRival: "Accountability",
    roastBullets: [
      "The forest video was rock bottom, somehow kept digging up",
      "Prime sells more than most legitimate beverage brands",
      "WWE actually gave him a contract. We live in a simulation.",
      "The redemption arc nobody asked for but we're witnessing anyway",
    ],
  },
  {
    id: "jake-paul",
    name: "Jake Paul",
    title: "YouTuber / Boxer",
    company: "Most Valuable Promotions",
    imageUrl: "/famous/celebrities/generated/jake-paul-card.png",
    score: 64,
    archetypeName: "Chaos Boxing PM",
    archetypeEmoji: "🥊",
    archetypeDescription: "Proving you can punch your way out of any PR crisis",
    element: "chaos",
    moves: [
      { name: "Fight Announcement", energyCost: 1, damage: 55, effect: "Creates PPV demand" },
      { name: "It's Everyday Bro", energyCost: 2, damage: 40, effect: "Cringe content, still viral" },
      { name: "Mike Tyson Call Out", energyCost: 2, damage: 70, effect: "Challenges legends" },
    ],
    stage: "Senior",
    weakness: "Real Boxers",
    flavor: "Made boxing somehow more chaotic than YouTube drama.",
    bangerQuote: "Fighting retired athletes for money is technically a business model.",
    naturalRival: "Professional boxers who trained their whole lives",
    roastBullets: [
      "Fights retirees and claims they're real boxing matches",
      "'It's Everyday Bro' was a crime against music",
      "The less talented Paul brother, which is saying something",
      "Somehow making actual money punching people, respect the hustle",
    ],
  },
  {
    id: "pewdiepie",
    name: "PewDiePie",
    title: "YouTuber",
    company: "Pewdie Productions",
    imageUrl: "/famous/celebrities/generated/pewdiepie-card.png",
    score: 82,
    archetypeName: "OG Content King",
    archetypeEmoji: "👊",
    archetypeDescription: "Screamed at video games until he was the biggest YouTuber. Retired.",
    element: "shipping",
    moves: [
      { name: "Bro Fist", energyCost: 1, damage: 50, effect: "Activates 111M subscribers" },
      { name: "Meme Review", energyCost: 2, damage: 70, effect: "Kills memes by reviewing them" },
      { name: "Subscribe War", energyCost: 2, damage: 80, effect: "Mobilizes internet army" },
    ],
    stage: "Elite",
    weakness: "Bridges",
    flavor: "The first to 100M subscribers. Retired because he felt like it.",
    bangerQuote: "Made screaming at horror games a $40M/year career, then just... stopped.",
    naturalRival: "T-Series",
    roastBullets: [
      "Retired from being the biggest YouTuber because he got bored",
      "The T-Series war was the most unhinged subscriber campaign ever",
      "Several controversies that would end normal careers, kept going",
      "Married Marzia and moved to Japan. Winning.",
    ],
  },
  {
    id: "david-beckham",
    name: "David Beckham",
    title: "Football Legend / Owner",
    company: "Inter Miami",
    imageUrl: "/famous/celebrities/generated/david-beckham-card.png",
    score: 87,
    archetypeName: "Pretty Boy Mogul",
    archetypeEmoji: "⚽",
    archetypeDescription: "Bent balls into nets, bent his image into a billion-dollar brand",
    element: "politics",
    moves: [
      { name: "Bend It", energyCost: 2, damage: 80, effect: "Curves any obstacle" },
      { name: "Brand Ambassador", energyCost: 1, damage: 50, effect: "Endorses literally everything" },
      { name: "Messi Signing", energyCost: 2, damage: 95, effect: "Recruits GOAT to Miami" },
    ],
    stage: "Elite",
    weakness: "Interviews",
    flavor: "Let Victoria handle the talking, focused on being pretty and rich.",
    bangerQuote: "Signed Messi to Inter Miami. The ultimate recruitment flex.",
    naturalRival: "Speaking publicly",
    roastBullets: [
      "Made being handsome and kicking a ball into billions",
      "The Messi signing made Inter Miami actually relevant",
      "Victoria does the talking for a reason",
      "Documentary showed he's obsessive about beekeeping now. Sure.",
    ],
  },
  {
    id: "bear-grylls",
    name: "Bear Grylls",
    title: "Survivalist / TV Host",
    company: "Bear Grylls Ventures",
    imageUrl: "/famous/celebrities/generated/bear-grylls-card.png",
    score: 73,
    archetypeName: "Pee Drinking PM",
    archetypeEmoji: "🏕️",
    archetypeDescription: "Will drink his own urine but won't drink the corporate Kool-Aid",
    element: "chaos",
    moves: [
      { name: "Drink Own Pee", energyCost: 1, damage: 45, effect: "Survives anything, dramatically" },
      { name: "Celebrity Drop", energyCost: 2, damage: 70, effect: "Makes celebs suffer for content" },
      { name: "Hotel Revelation", energyCost: 2, damage: 60, effect: "Actually stays in hotels" },
    ],
    stage: "Elite",
    weakness: "Hotels",
    flavor: "Sleeps in dead animals on TV, sleeps in hotels off camera.",
    bangerQuote: "Made a career drinking pee on TV while staying at Four Seasons off-camera.",
    naturalRival: "Comfortable accommodation",
    roastBullets: [
      "The pee drinking became his entire brand",
      "Turns out the 'survival' show had hotels nearby",
      "Every celebrity episode is just rich people pretending to struggle",
      "Still probably more survival skills than most tech bros",
    ],
  },
  {
    id: "james-corden",
    name: "James Corden",
    title: "TV Host / Actor",
    company: "Fulwell 73",
    imageUrl: "/famous/celebrities/generated/james-corden-card.png",
    score: 62,
    archetypeName: "Carpool Karaoke PM",
    archetypeEmoji: "🚗",
    archetypeDescription: "Somehow parlayed singing in cars into a late night empire",
    element: "politics",
    moves: [
      { name: "Carpool Karaoke", energyCost: 2, damage: 65, effect: "Simple concept, massive reach" },
      { name: "Restaurant Ban", energyCost: 1, damage: 40, effect: "Gets banned from establishments" },
      { name: "British Charm", energyCost: 1, damage: 45, effect: "Works... on some people" },
    ],
    stage: "Senior",
    weakness: "Restaurant Staff",
    flavor: "Got banned from a restaurant. That's a specific kind of famous.",
    bangerQuote: "Made driving and singing into a format. Actually innovative.",
    naturalRival: "Service industry workers",
    roastBullets: [
      "Carpool Karaoke is his only bit and it worked",
      "The restaurant ban stories are wild",
      "Left America because we were done with him",
      "Somehow less annoying in the UK where he started",
    ],
  },
  {
    id: "dr-phil",
    name: "Dr. Phil",
    title: "TV Host",
    company: "Peteski Productions",
    imageUrl: "/famous/celebrities/generated/dr-phil-card.png",
    score: 66,
    archetypeName: "Exploitation Expert",
    archetypeEmoji: "🧠",
    archetypeDescription: "Exploits troubled people for content, calls it help",
    element: "data",
    moves: [
      { name: "Cash Me Outside", energyCost: 2, damage: 75, effect: "Creates viral chaos" },
      { name: "Ranch Threat", energyCost: 2, damage: 65, effect: "Sends kids to troubled facility" },
      { name: "Mustache Wisdom", energyCost: 1, damage: 40, effect: "Obvious advice, dramatically" },
    ],
    stage: "Senior",
    weakness: "Credentials",
    flavor: "Not a licensed psychologist, but plays one on TV for millions.",
    bangerQuote: "Made millions giving obvious advice to people who need real help.",
    naturalRival: "Actual licensed therapists",
    roastBullets: [
      "Created Bhad Bhabie and has to live with that",
      "The 'ranch' recommendations aged poorly",
      "Not actually licensed to practice psychology anywhere",
      "Oprah's creation that maybe shouldn't have been created",
    ],
  },
  {
    id: "gwyneth-paltrow",
    name: "Gwyneth Paltrow",
    title: "Actress / Entrepreneur",
    company: "Goop",
    imageUrl: "/famous/celebrities/generated/gwyneth-paltrow-card.png",
    score: 69,
    archetypeName: "Jade Egg Queen",
    archetypeEmoji: "🥚",
    archetypeDescription: "Selling vaginal eggs and candles that smell like her. Somehow profitable.",
    element: "vision",
    moves: [
      { name: "Goop Launch", energyCost: 2, damage: 70, effect: "Sells questionable wellness" },
      { name: "Conscious Uncoupling", energyCost: 1, damage: 45, effect: "Rebrands divorce" },
      { name: "Ski Trial Victory", energyCost: 2, damage: 75, effect: "Wins lawsuit stylishly" },
    ],
    stage: "Senior",
    weakness: "Science",
    flavor: "Built a wellness empire on vibes and pseudoscience.",
    bangerQuote: "Sold a candle called 'This Smells Like My Vagina' and it sold out.",
    naturalRival: "FDA regulations",
    roastBullets: [
      "The vagina candle was a real product that made real money",
      "Jade eggs for your vagina. That was a thing she sold.",
      "Won a lawsuit by being insufferably calm on the stand",
      "'Conscious uncoupling' is the most Goop way to say divorce",
    ],
  },
  {
    id: "matthew-mcconaughey",
    name: "Matthew McConaughey",
    title: "Actor",
    company: "J.K. Livin",
    imageUrl: "/famous/celebrities/generated/matthew-mcconaughey-card.png",
    score: 78,
    archetypeName: "Alright Alright PM",
    archetypeEmoji: "🤙",
    archetypeDescription: "Went from rom-coms to Oscar winner through sheer chill energy",
    element: "vision",
    moves: [
      { name: "Alright Alright", energyCost: 1, damage: 45, effect: "Remains perpetually chill" },
      { name: "McConaissance", energyCost: 2, damage: 85, effect: "Reinvents entire career" },
      { name: "Lincoln Ads", energyCost: 1, damage: 40, effect: "Makes car ads philosophical" },
    ],
    stage: "Elite",
    weakness: "Shirts",
    flavor: "The McConaissance proved everyone wrong. Then the Lincoln ads happened.",
    bangerQuote: "Pivoted from shirtless rom-coms to Oscar winner through refusing to wear shirts.",
    naturalRival: "Upper body clothing",
    roastBullets: [
      "The McConaissance was a legitimate career resurrection",
      "Those Lincoln commercials were unhinged in the best way",
      "Wrote a memoir that's somehow both profound and rambling",
      "Considered running for Texas governor. Texas gonna Texas.",
    ],
  },
  {
    id: "neil-degrasse-tyson",
    name: "Neil deGrasse Tyson",
    title: "Astrophysicist",
    company: "Hayden Planetarium",
    imageUrl: "/famous/celebrities/generated/neil-degrasse-tyson-card.png",
    score: 75,
    archetypeName: "Actually Astronomer",
    archetypeEmoji: "🔭",
    archetypeDescription: "Will 'actually' your sci-fi movie until you hate the universe",
    element: "data",
    moves: [
      { name: "Well Actually", energyCost: 1, damage: 50, effect: "Corrects minor inaccuracies" },
      { name: "Cosmos Update", energyCost: 2, damage: 70, effect: "Makes space accessible" },
      { name: "Tweet Correction", energyCost: 1, damage: 45, effect: "Ruins everyone's fun" },
    ],
    stage: "Elite",
    weakness: "Fun",
    flavor: "Made space cool, then made space insufferable with corrections.",
    bangerQuote: "Will ruin any movie by explaining why the science is wrong.",
    naturalRival: "Hollywood physics",
    roastBullets: [
      "The 'um actually' of astrophysics",
      "Tweets like someone who needs to be the smartest in every room",
      "Made science accessible then made it annoying",
      "Cosmos was great, his Twitter is exhausting",
    ],
  },
  {
    id: "bill-nye",
    name: "Bill Nye",
    title: "Science Guy",
    company: "Bill Nye",
    imageUrl: "/famous/celebrities/generated/bill-nye-card.png",
    score: 77,
    archetypeName: "Science Guy PM",
    archetypeEmoji: "🔬",
    archetypeDescription: "Taught millennials science, now debates climate deniers for content",
    element: "data",
    moves: [
      { name: "Bill Bill Bill", energyCost: 1, damage: 50, effect: "Nostalgic activation" },
      { name: "Climate Debate", energyCost: 2, damage: 65, effect: "Explains obvious science" },
      { name: "Netflix Reboot", energyCost: 2, damage: 55, effect: "Tries to recapture magic" },
    ],
    stage: "Elite",
    weakness: "Climate Deniers",
    flavor: "The Science Guy grew up angry at people who ignore science.",
    bangerQuote: "Went from teaching kids science to yelling at adults to believe science.",
    naturalRival: "Science deniers",
    roastBullets: [
      "Millennials will defend this man with their lives",
      "The Netflix show was... a choice",
      "Now just debates people who don't believe in climate change",
      "The bow tie is doing a lot of heavy lifting",
    ],
  },
  {
    id: "gary-vaynerchuk",
    name: "Gary Vaynerchuk",
    title: "Entrepreneur / Speaker",
    company: "VaynerMedia",
    imageUrl: "/famous/celebrities/generated/gary-vaynerchuk-card.png",
    score: 71,
    archetypeName: "Hustle Bro Supreme",
    archetypeEmoji: "💯",
    archetypeDescription: "Yells about hustle culture while selling hustle culture",
    element: "chaos",
    moves: [
      { name: "Document Don't Create", energyCost: 1, damage: 45, effect: "Films everything always" },
      { name: "NFT Pivot", energyCost: 2, damage: 60, effect: "VeeFriends enters chat" },
      { name: "Empathy Speech", energyCost: 2, damage: 70, effect: "Motivational intensity" },
    ],
    stage: "Elite",
    weakness: "Sleep",
    flavor: "Sold wine, then sold motivation, then sold NFTs. Always selling.",
    bangerQuote: "The patron saint of yelling 'hustle' at people who already work too much.",
    naturalRival: "Work-life balance",
    roastBullets: [
      "Pivoted from wine to NFTs faster than you can say 'grift'",
      "Tells people to hustle while being already rich from wine money",
      "VeeFriends is... definitely a thing that exists",
      "Content output suggests he doesn't sleep, which tracks",
    ],
  },
  {
    id: "floyd-mayweather",
    name: "Floyd Mayweather",
    title: "Boxer",
    company: "Mayweather Promotions",
    imageUrl: "/famous/celebrities/generated/floyd-mayweather-card.png",
    score: 80,
    archetypeName: "Money PM",
    archetypeEmoji: "💰",
    archetypeDescription: "50-0 record and won't let you forget about the money",
    element: "data",
    moves: [
      { name: "Money Count", energyCost: 1, damage: 45, effect: "Flexes earnings publicly" },
      { name: "Defensive Master", energyCost: 2, damage: 75, effect: "Untouchable strategy" },
      { name: "Exhibition Match", energyCost: 2, damage: 65, effect: "Fights anyone for cash" },
    ],
    stage: "Elite",
    weakness: "Reading",
    flavor: "Undefeated in boxing, challenged by written word.",
    bangerQuote: "50-0 but makes the most money fighting YouTubers now.",
    naturalRival: "Literacy requirements",
    roastBullets: [
      "Shows his money because talking is harder",
      "Fights YouTubers for paychecks now, no shame",
      "The reading struggles are well documented",
      "Still somehow the smartest businessman in boxing",
    ],
  },
  {
    id: "adele",
    name: "Adele",
    title: "Artist",
    company: "Columbia Records",
    imageUrl: "/famous/celebrities/generated/adele-card.png",
    score: 89,
    archetypeName: "Heartbreak Hits PM",
    archetypeEmoji: "🎤",
    archetypeDescription: "Makes everyone cry about her relationships for billions",
    element: "vision",
    moves: [
      { name: "Hello From Other Side", energyCost: 2, damage: 85, effect: "Universal emotional damage" },
      { name: "Vegas Residency", energyCost: 2, damage: 75, effect: "Postpones, makes more money" },
      { name: "Album Drop", energyCost: 2, damage: 90, effect: "Breaks streaming records" },
    ],
    stage: "Elite",
    weakness: "Happy Relationships",
    flavor: "Needs to be sad to make hits. The art requires suffering.",
    bangerQuote: "Every breakup becomes a billion-dollar album. Date her exes, not her.",
    naturalRival: "Happiness",
    roastBullets: [
      "Her exes have funded multiple mansions",
      "Postponed Vegas residency and somehow became more in demand",
      "The voice is undeniable, the emotional damage is intentional",
      "Happy Adele might never make another album",
    ],
  },
  {
    id: "donald-trump",
    name: "Donald Trump",
    title: "Former President / Businessman",
    company: "The Trump Organization",
    imageUrl: "/famous/celebrities/generated/donald-trump-card.png",
    score: 70,
    archetypeName: "Chaos CEO",
    archetypeEmoji: "🍊",
    archetypeDescription: "From reality TV to the White House. The ultimate chaotic pivot.",
    element: "chaos",
    moves: [
      { name: "You're Fired", energyCost: 1, damage: 55, effect: "Terminates without warning" },
      { name: "Tweet Storm", energyCost: 2, damage: 75, effect: "Dominates news cycle" },
      { name: "Art of The Deal", energyCost: 2, damage: 65, effect: "Claims negotiation victory" },
    ],
    stage: "Elite",
    weakness: "Criticism",
    flavor: "From Apprentice host to President. America is wild.",
    bangerQuote: "Turned Twitter beefs and reality TV into the actual presidency.",
    naturalRival: "Fact-checkers",
    roastBullets: [
      "Reality TV to President is the most American career path",
      "The tan is structural at this point",
      "Bankruptcies are just 'strategic restructuring'",
      "Still dominates headlines whether you want him to or not",
    ],
  },
  {
    id: "ed-sheeran",
    name: "Ed Sheeran",
    title: "Artist",
    company: "Atlantic Records",
    imageUrl: "/famous/celebrities/generated/ed-sheeran-card.png",
    score: 81,
    archetypeName: "Ginger Hitmaker",
    archetypeEmoji: "🎸",
    archetypeDescription: "Looks like your mate from school, has billions of streams",
    element: "shipping",
    moves: [
      { name: "Loop Pedal Solo", energyCost: 2, damage: 75, effect: "One-man band mode" },
      { name: "Wedding Song", energyCost: 1, damage: 50, effect: "Becomes first dance standard" },
      { name: "Cameo Appearance", energyCost: 1, damage: 45, effect: "Shows up in Game of Thrones" },
    ],
    stage: "Elite",
    weakness: "Originality Claims",
    flavor: "Makes songs for everyone's wedding that sound vaguely the same.",
    bangerQuote: "Became a billionaire making music that sounds like every other song.",
    naturalRival: "Copyright lawyers",
    roastBullets: [
      "Every song sounds like your first dance at a wedding",
      "The Game of Thrones cameo was unnecessary",
      "Gets sued for plagiarism constantly, keeps winning",
      "Looks like he should be asking for spare change, worth $200M",
    ],
  },
  {
    id: "jennifer-lopez",
    name: "Jennifer Lopez",
    title: "Artist / Actress",
    company: "Nuyorican Productions",
    imageUrl: "/famous/celebrities/generated/jennifer-lopez-card.png",
    score: 79,
    archetypeName: "Jenny From Block",
    archetypeEmoji: "💃",
    archetypeDescription: "Still Jenny from the block, just with a much bigger block",
    element: "shipping",
    moves: [
      { name: "Triple Threat", energyCost: 2, damage: 75, effect: "Acts, sings, dances, simultaneously" },
      { name: "Ben Affleck Redux", energyCost: 2, damage: 70, effect: "Relationship comeback tour" },
      { name: "Super Bowl Show", energyCost: 2, damage: 80, effect: "Headlines at 50+" },
    ],
    stage: "Elite",
    weakness: "Aging",
    flavor: "Refuses to age like a normal human. Suspicious.",
    bangerQuote: "Got back with Ben Affleck 20 years later. The ultimate delayed ship.",
    naturalRival: "Father Time",
    roastBullets: [
      "Looks the same as she did 20 years ago. Suspicious.",
      "The Bennifer reunion was the content we didn't know we needed",
      "Super Bowl halftime show at 50 was a flex",
      "Still claims to be Jenny from the block with a $400M net worth",
    ],
  },
  {
    id: "johnny-depp",
    name: "Johnny Depp",
    title: "Actor",
    company: "Infinitum Nihil",
    imageUrl: "/famous/celebrities/generated/johnny-depp-card.png",
    score: 72,
    archetypeName: "Pirates Pensioner",
    archetypeEmoji: "🏴‍☠️",
    archetypeDescription: "Made Jack Sparrow iconic, made court testimony more iconic",
    element: "chaos",
    moves: [
      { name: "Why Is Rum Gone", energyCost: 1, damage: 45, effect: "Questions resource allocation" },
      { name: "Court Victory", energyCost: 2, damage: 85, effect: "Wins defamation publicly" },
      { name: "Character Acting", energyCost: 2, damage: 70, effect: "Becomes unrecognizable" },
    ],
    stage: "Elite",
    weakness: "Relationships",
    flavor: "The trial became bigger content than any of his movies.",
    bangerQuote: "Won a lawsuit but the real prize was the memes we made along the way.",
    naturalRival: "Amber Heard",
    roastBullets: [
      "The trial was better content than most Netflix shows",
      "Jack Sparrow for like 6 movies straight",
      "Court testimony spawned infinite memes",
      "Actually a decent artist? Who knew.",
    ],
  },
];

// Get a random card for showcase
export function getRandomCelebrityCard(): CelebrityCard {
  return CELEBRITY_CARDS[Math.floor(Math.random() * CELEBRITY_CARDS.length)];
}

// Get card by ID
export function getCelebrityCardById(id: string): CelebrityCard | undefined {
  return CELEBRITY_CARDS.find(card => card.id === id);
}

// Search celebrity cards by name (case-insensitive fuzzy match)
export function searchCelebrityCards(query: string): CelebrityCard[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return [];

  return CELEBRITY_CARDS.filter(card => {
    const name = card.name.toLowerCase();
    const company = card.company.toLowerCase();
    return name.includes(normalizedQuery) || company.includes(normalizedQuery);
  }).slice(0, 5);
}
