/**
 * Famous PM/CEO Roast Cards
 *
 * Pre-generated cards for famous tech leaders for entertainment.
 * These are fictional roasts for entertainment purposes only.
 */

import { PMElement, PMMove } from "./types";

export interface FamousCard {
  id: string;
  name: string;
  title: string;
  company: string;
  imageUrl: string; // Path to profile image
  score: number;
  archetypeName: string;
  archetypeEmoji: string;
  archetypeDescription: string;
  element: PMElement;
  moves: PMMove[];
  stage: string;
  weakness: string;
  flavor: string;
  bangerQuote: string;
  naturalRival: string;
  roastBullets: string[];
}

// Helper to determine stage from score
function getStage(score: number): string {
  if (score >= 95) return "Mythical";
  if (score >= 90) return "Legendary";
  if (score >= 80) return "Elite";
  return "Senior";
}

export const FAMOUS_CARDS: FamousCard[] = [
  // === ORIGINAL CARDS ===
  {
    id: "brian-chesky",
    name: "Brian Chesky",
    title: "CEO & Co-founder",
    company: "Airbnb",
    imageUrl: "/famous/generated/brian-card.png",
    score: 94,
    archetypeName: "The Design Dictator",
    archetypeEmoji: "🎨",
    archetypeDescription: "Believes every problem can be solved with better typography and a 47-slide deck about 'belonging'",
    element: "vision",
    moves: [
      { name: "Founder Mode Activate", energyCost: 2, damage: 60, effect: "Bypasses all middle management" },
      { name: "Pixel Perfect Rage", energyCost: 3, damage: 80, effect: "Redesigns opponent's entire product roadmap" },
      { name: "Snow White Strategy", energyCost: 4, damage: 120, effect: "Storyboards the competition into oblivion" },
    ],
    stage: "Legendary",
    weakness: "Hotels",
    flavor: "Once redesigned an air mattress into a $100B company. Still thinks he could've made the mattress better.",
    bangerQuote: "Your Figma skills are not a substitute for a business model, but damn if Brian didn't prove otherwise.",
    naturalRival: "Marriott's entire marketing budget",
    roastBullets: [
      "Turned 'strangers sleeping in your house' from a horror movie plot into a $100B company",
      "Has definitely fired someone over font kerning",
      "The only CEO who treats every all-hands like a TED talk about the meaning of human connection",
      "Invented 'Founder Mode' because 'micromanaging with charisma' didn't fit on the blog post title",
    ],
  },
  {
    id: "demis-hassabis",
    name: "Demis Hassabis",
    title: "CEO & Co-founder",
    company: "Google DeepMind",
    imageUrl: "/famous/generated/demis-card.png",
    score: 99,
    archetypeName: "The Galaxy Brain",
    archetypeEmoji: "🧠",
    archetypeDescription: "Solving intelligence so he can finally have someone smart enough to talk to",
    element: "data",
    moves: [
      { name: "Chess Grandmaster Stare", energyCost: 1, damage: 40, effect: "Makes opponent question their IQ" },
      { name: "Nobel Prize Drop", energyCost: 3, damage: 100, effect: "Stuns all critics for 3 turns" },
      { name: "AlphaFold Flex", energyCost: 4, damage: 150, effect: "Solves opponent's entire industry" },
    ],
    stage: "Mythical",
    weakness: "Small talk",
    flavor: "Built an AI that beat Go champions, solved protein folding, and still somehow has to explain to his parents what he does.",
    bangerQuote: "Won a Nobel Prize for AI and still gets asked 'but can it write my emails?' at dinner parties.",
    naturalRival: "Anyone who says 'AGI is just hype'",
    roastBullets: [
      "Casually revolutionized biology between chess tournaments",
      "Has a Nobel Prize and a Nature paper but LinkedIn still suggests he 'complete his profile'",
      "The only person whose 'I was a child prodigy' story is somehow underselling it",
      "Solved protein folding but still can't solve why Google keeps killing his favorite products",
    ],
  },
  {
    id: "lenny-rachitsky",
    name: "Lenny Rachitsky",
    title: "Newsletter Guy",
    company: "Lenny's Newsletter",
    imageUrl: "/famous/generated/lenny-card.png",
    score: 88,
    archetypeName: "The PM Whisperer",
    archetypeEmoji: "🎙️",
    archetypeDescription: "Turned 'I got laid off from Airbnb' into a media empire by asking other PMs about their frameworks",
    element: "strategy",
    moves: [
      { name: "Podcast Plug", energyCost: 1, damage: 30, effect: "Gains 10K subscribers" },
      { name: "Framework Overload", energyCost: 2, damage: 60, effect: "Buries opponent in 2x2 matrices" },
      { name: "Benchmark Blast", energyCost: 3, damage: 90, effect: "Makes opponent feel inadequate about their metrics" },
    ],
    stage: "Elite",
    weakness: "Unstructured conversations",
    flavor: "Interviewed every PM who ever shipped anything, synthesized it into frameworks, and now every PM sounds exactly the same. You're welcome.",
    bangerQuote: "Made more money asking 'what metrics do you track?' than most PMs make actually tracking metrics.",
    naturalRival: "PMs with actual opinions",
    roastBullets: [
      "Became the most influential PM by... not being a PM anymore",
      "Has asked 'what's your framework for X' so many times it's now his actual personality",
      "The only person who can make 'I aggregate other people's insights' sound like thought leadership",
      "Proof that the best career move in product is to stop doing product and just talk about it",
    ],
  },
  {
    id: "reid-hoffman",
    name: "Reid Hoffman",
    title: "Partner & LinkedIn Guy",
    company: "Greylock Partners",
    imageUrl: "/famous/generated/reid-card.png",
    score: 91,
    archetypeName: "The Network Node",
    archetypeEmoji: "🕸️",
    archetypeDescription: "Built the world's largest professional cringe repository and somehow made billions",
    element: "politics",
    moves: [
      { name: "LinkedIn Connection", energyCost: 1, damage: 20, effect: "Forces opponent to accept unwanted networking request" },
      { name: "Board Seat Shuffle", energyCost: 3, damage: 80, effect: "Appears on opponent's cap table" },
      { name: "Blitzscaling Bomb", energyCost: 4, damage: 130, effect: "Burns cash faster than opponent can react" },
    ],
    stage: "Legendary",
    weakness: "AI ethics questions",
    flavor: "Created a platform where people unironically write 'I'm humbled to announce' and it's worth more than most countries.",
    bangerQuote: "Invented the place where your weird uncle posts motivational quotes next to crypto scams, and VCs call it 'professional networking'.",
    naturalRival: "Twitter/X stealing his thought leaders",
    roastBullets: [
      "Made a website for job hunting and somehow it became a platform for people to write 5-paragraph posts about being fired",
      "The godfather of 'agree?' posts",
      "Blitzscaled his way through every ethical question by just going faster",
      "Wrote a book about networks and then invested in AI that might make networks obsolete",
    ],
  },
  {
    id: "elon-musk",
    name: "Elon Musk",
    title: "Chief Twit / Technoking",
    company: "Tesla / SpaceX / X",
    imageUrl: "/famous/generated/elon-card.png",
    score: 97,
    archetypeName: "The Chaos Emperor",
    archetypeEmoji: "🚀",
    archetypeDescription: "Runs 5 companies, posts at 3am, and somehow convinced people that sleeping at the office is sigma behavior",
    element: "chaos",
    moves: [
      { name: "3AM Tweet Storm", energyCost: 1, damage: 45, effect: "Tanks own stock price, confuses everyone" },
      { name: "Mass Layoff", energyCost: 2, damage: 80, effect: "Reduces opponent's team by 80%" },
      { name: "First Principles Rant", energyCost: 4, damage: 150, effect: "Makes opponent question everything they know" },
    ],
    stage: "Mythical",
    weakness: "Regulators",
    flavor: "The only man who can mass layoff an entire company and have people thank him for it.",
    bangerQuote: "Bought Twitter to fix free speech, turned it into the world's most expensive shitposting platform.",
    naturalRival: "The SEC, sleep, and anyone who asks about Cybertruck windows",
    roastBullets: [
      "Paid $44 billion for a website, immediately made it worth $12 billion, called it a win",
      "Has 11 kids but still finds time to post memes at 2am like a teenager",
      "Promised self-driving cars by 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024... any day now",
      "The only CEO whose HR strategy is 'tweet something wild and see who quits'",
    ],
  },
  {
    id: "mark-zuckerberg",
    name: "Mark Zuckerberg",
    title: "CEO & Founder",
    company: "Meta",
    imageUrl: "/famous/generated/mark-card.png",
    score: 93,
    archetypeName: "The Metaverse Missionary",
    archetypeEmoji: "🤖",
    archetypeDescription: "Spent $50B trying to make people wear VR headsets to attend meetings they already hate",
    element: "data",
    moves: [
      { name: "Congressional Testimony", energyCost: 1, damage: 30, effect: "Drinks water robotically, survives another hearing" },
      { name: "Privacy Pivot", energyCost: 2, damage: 70, effect: "Harvests opponent's data while apologizing" },
      { name: "Metaverse Rebrand", energyCost: 4, damage: 100, effect: "Changes company name, nothing else changes" },
    ],
    stage: "Legendary",
    weakness: "Human emotions",
    flavor: "Started by rating college girls, now rates your grandma's engagement metrics.",
    bangerQuote: "Convinced 3 billion people to give him their data, then wondered why they don't trust him.",
    naturalRival: "Apple's privacy features and anyone who asks him to smile naturally",
    roastBullets: [
      "Renamed the company 'Meta' so people would stop calling him the Facebook guy. It didn't work.",
      "His Senate testimony water-drinking technique has been studied by robots learning human behavior",
      "Spent more on the metaverse than NASA's entire annual budget, created Wii avatars with legs",
      "The only billionaire who looks more comfortable fighting in a cage than making small talk",
    ],
  },
  {
    id: "dario-amodei",
    name: "Dario Amodei",
    title: "CEO & Co-founder",
    company: "Anthropic",
    imageUrl: "/famous/generated/dario-card.png",
    score: 96,
    archetypeName: "The Safety Sage",
    archetypeEmoji: "🛡️",
    archetypeDescription: "Left OpenAI because it wasn't safe enough, immediately built an even more powerful AI",
    element: "strategy",
    moves: [
      { name: "Safety Theater", energyCost: 2, damage: 60, effect: "Publishes 50-page paper explaining why this is fine" },
      { name: "Constitutional AI", energyCost: 3, damage: 90, effect: "Makes opponent's AI politely refuse to compete" },
      { name: "Scaling Laws Lecture", energyCost: 4, damage: 130, effect: "Bores opponent into submission with math" },
    ],
    stage: "Legendary",
    weakness: "Moving fast",
    flavor: "The 'responsible AI' guy who keeps making AI more powerful. The cognitive dissonance is a feature, not a bug.",
    bangerQuote: "We're building the most powerful AI in history, but don't worry, we wrote a constitution for it.",
    naturalRival: "OpenAI's marketing budget and anyone who ships without a safety review",
    roastBullets: [
      "Left OpenAI over safety concerns, raised $7B to build something even more capable. Make it make sense.",
      "Writes blog posts about AI risk while his company races to build AGI. The irony writes itself.",
      "Has the energy of a physics professor who's seen the equations and knows we're all doomed",
      "Named his AI 'Claude' because 'Definitely Not Skynet' was already taken",
    ],
  },
  {
    id: "jack-dorsey",
    name: "Jack Dorsey",
    title: "Former CEO & Founder",
    company: "Twitter / Block",
    imageUrl: "/famous/generated/jack-card.png",
    score: 85,
    archetypeName: "The Zen Billionaire",
    archetypeEmoji: "🧘",
    archetypeDescription: "Meditates for 2 hours daily while his platforms burn. Namaste.",
    element: "vision",
    moves: [
      { name: "Edit Button Denial", energyCost: 1, damage: 40, effect: "Refuses to add obvious feature for 15 years" },
      { name: "Silent Retreat", energyCost: 2, damage: 50, effect: "Disappears for a month, company continues without noticing" },
      { name: "Bitcoin Maximalism", energyCost: 3, damage: 85, effect: "Converts opponent's treasury to BTC" },
    ],
    stage: "Elite",
    weakness: "Moderation decisions",
    flavor: "Built a platform for free speech, then spent a decade trying to figure out what that means.",
    bangerQuote: "Ran two public companies part-time while doing ice baths and fasting. Peak Silicon Valley monk energy.",
    naturalRival: "Anyone who asks why Twitter didn't have an edit button for 16 years",
    roastBullets: [
      "Was CEO of two companies simultaneously and both somehow felt neglected",
      "His content moderation strategy was 'meditate on it and hope it goes away'",
      "Sold Twitter to Elon, then spent the next year subtweeting about how it's being run",
      "Walks to work barefoot, eats one meal a day, and wonders why people think he's out of touch",
    ],
  },
  {
    id: "nikita-bier",
    name: "Nikita Bier",
    title: "Serial App Flipper",
    company: "TBH / Gas / ???",
    imageUrl: "/famous/generated/nikita-card.png",
    score: 89,
    archetypeName: "The Teen Whisperer",
    archetypeEmoji: "📱",
    archetypeDescription: "Has sold more apps to Facebook than most people have downloaded",
    element: "shipping",
    moves: [
      { name: "Gen Z Decoder", energyCost: 1, damage: 45, effect: "Understands what teens want before they do" },
      { name: "Viral Loop Deploy", energyCost: 2, damage: 75, effect: "App spreads through every high school in America" },
      { name: "Acqui-hire Bait", energyCost: 3, damage: 90, effect: "Gets bought before having to figure out monetization" },
    ],
    stage: "Elite",
    weakness: "Long-term retention",
    flavor: "The only person who's figured out that the real product is the acquisition, not the app.",
    bangerQuote: "Built two apps, sold both to Big Tech, and made it look easy. The rest of us are just playing checkers.",
    naturalRival: "App Store reviewers and anyone who asks about DAU after month 3",
    roastBullets: [
      "Has a better exit-to-effort ratio than anyone in Silicon Valley history",
      "Builds apps for teens, sells to Facebook, watches them die. Rinse and repeat.",
      "His growth hack is making apps so viral that Big Tech has to buy them to understand young people",
      "The only founder whose business model is literally 'get acquired before we have to make money'",
    ],
  },

  // === TIER 1: ICONIC TECH FIGURES ===
  {
    id: "paul-graham",
    name: "Paul Graham",
    title: "Co-founder",
    company: "Y Combinator",
    imageUrl: "/famous/generated/paul-graham-card.png",
    score: 96,
    archetypeName: "The Essay Evangelist",
    archetypeEmoji: "📝",
    archetypeDescription: "Turned 'writing long essays about startups' into a multi-billion dollar empire",
    element: "vision",
    moves: [
      { name: "Essay Drop", energyCost: 2, damage: 70, effect: "Changes the entire startup discourse" },
      { name: "YC Rejection", energyCost: 1, damage: 50, effect: "Motivates opponent to prove them wrong" },
      { name: "Founder Filter", energyCost: 3, damage: 100, effect: "Identifies true builders instantly" },
    ],
    stage: "Mythical",
    weakness: "Twitter character limits",
    flavor: "Wrote the book on startups. Literally. Several of them. Will tell you about it.",
    bangerQuote: "Invented the startup accelerator, then spent 20 years explaining why everyone else is doing it wrong.",
    naturalRival: "Founders who don't read his essays",
    roastBullets: [
      "Has more hot takes on startups than actual startups at this point",
      "Every essay somehow ends with 'and that's why YC companies succeed'",
      "Pioneered the 'build something people want' advice that 10,000 Medium articles have since restated",
      "The only person whose tweets are longer than his essays",
    ],
  },
  {
    id: "marc-andreessen",
    name: "Marc Andreessen",
    title: "Co-founder",
    company: "a16z",
    imageUrl: "/famous/generated/marc-andreessen-card.png",
    score: 95,
    archetypeName: "The Techno-Optimist Supreme",
    archetypeEmoji: "🦾",
    archetypeDescription: "Believes technology will solve everything, including the problems technology creates",
    element: "vision",
    moves: [
      { name: "Manifesto Mode", energyCost: 3, damage: 90, effect: "Converts skeptics through sheer word count" },
      { name: "Portfolio Power", energyCost: 2, damage: 70, effect: "Funds both sides of the competition" },
      { name: "Browser Legacy", energyCost: 1, damage: 40, effect: "Reminds everyone he invented the web browser" },
    ],
    stage: "Mythical",
    weakness: "Regulation",
    flavor: "Invented the web browser, then decided the real product was hot takes.",
    bangerQuote: "Wrote the 'software is eating the world' essay and then ate the rest of the world with investments.",
    naturalRival: "Anyone who questions tech",
    roastBullets: [
      "Tweets like he's being paid per word (he probably is, indirectly)",
      "The 'Techno-Optimist Manifesto' was just his drafts folder published by accident",
      "Has funded both sides of every tech debate, just to be safe",
      "Profile picture hasn't changed since web 1.0",
    ],
  },
  {
    id: "naval-ravikant",
    name: "Naval Ravikant",
    title: "Co-founder",
    company: "AngelList",
    imageUrl: "/famous/generated/naval-ravikant-card.png",
    score: 91,
    archetypeName: "The Philosopher King",
    archetypeEmoji: "🧘",
    archetypeDescription: "Turned wealth advice into a spiritual practice and somehow made it work",
    element: "strategy",
    moves: [
      { name: "Tweetstorm of Wisdom", energyCost: 1, damage: 45, effect: "Spawns a thousand podcast episodes" },
      { name: "Wealth Formula", energyCost: 2, damage: 65, effect: "Makes opponent question their career choices" },
      { name: "Leverage Lecture", energyCost: 3, damage: 95, effect: "Explains code, media, capital, and labor" },
    ],
    stage: "Legendary",
    weakness: "Stock tip seekers",
    flavor: "Made millions, then decided the real treasure was the wisdom we shared along the way.",
    bangerQuote: "Built AngelList to fund startups, now funds your existential crisis instead.",
    naturalRival: "Hustle culture",
    roastBullets: [
      "Every tweet sounds like it should be on a motivational poster in a WeWork",
      "Somehow made 'be wealthy' sound like a spiritual journey",
      "The tweetstorm that became an almanac that became a personality",
      "Meditation advice from a guy worth hundreds of millions hits different",
    ],
  },
  {
    id: "sam-altman",
    name: "Sam Altman",
    title: "CEO",
    company: "OpenAI",
    imageUrl: "/famous/generated/sam-altman-card.png",
    score: 98,
    archetypeName: "The AGI Whisperer",
    archetypeEmoji: "🤖",
    archetypeDescription: "Building the thing that might end humanity, but with good vibes",
    element: "vision",
    moves: [
      { name: "Board Room Survivor", energyCost: 2, damage: 80, effect: "Returns stronger from any firing" },
      { name: "GPT Announcement", energyCost: 3, damage: 100, effect: "Breaks the entire internet" },
      { name: "AGI Teaser", energyCost: 4, damage: 140, effect: "Keeps everyone guessing for years" },
    ],
    stage: "Mythical",
    weakness: "Board meetings",
    flavor: "Got fired and rehired in the same week. That's founder mode.",
    bangerQuote: "Running YC was just the tutorial level. Now he's playing civilization on hard mode.",
    naturalRival: "AI doomers (and his own board)",
    roastBullets: [
      "Speedrunning the 'controversial tech CEO' achievement tree",
      "Got fired and came back stronger like a Silicon Valley Jesus",
      "Building AGI with the energy of 'we'll figure out the guardrails later'",
      "The only CEO whose board drama had more plot twists than Game of Thrones",
    ],
  },
  {
    id: "garry-tan",
    name: "Garry Tan",
    title: "CEO",
    company: "Y Combinator",
    imageUrl: "/famous/generated/garry-tan-card.png",
    score: 88,
    archetypeName: "The YC Revivalist",
    archetypeEmoji: "⚡",
    archetypeDescription: "Brought the startup energy back to YC and the hot takes back to Twitter",
    element: "shipping",
    moves: [
      { name: "SF Politics Battle", energyCost: 2, damage: 65, effect: "Enters local government discourse" },
      { name: "Founder Rally", energyCost: 1, damage: 45, effect: "Inspires a generation to build" },
      { name: "YC Batch Launch", energyCost: 3, damage: 90, effect: "Unleashes hundreds of startups" },
    ],
    stage: "Elite",
    weakness: "SF city politics",
    flavor: "Left YC, came back as the boss. That's the real founder journey.",
    bangerQuote: "Went from YC partner to VC to CEO of YC. Speedran the whole accelerator.",
    naturalRival: "SF Board of Supervisors",
    roastBullets: [
      "Fighting SF politics with the same intensity most people reserve for product launches",
      "The only YC CEO who might actually fight someone (verbally) (on Twitter)",
      "Brought the 'move fast and break things' energy to city government advocacy",
      "His tweet-to-policy-change ratio is actually impressive",
    ],
  },
  {
    id: "balaji-srinivasan",
    name: "Balaji Srinivasan",
    title: "Angel Investor",
    company: "Ex-Coinbase CTO",
    imageUrl: "/famous/generated/balaji-srinivasan-card.png",
    score: 89,
    archetypeName: "The Network State Prophet",
    archetypeEmoji: "🌐",
    archetypeDescription: "Predicting the future so hard he's building it himself, whether we like it or not",
    element: "chaos",
    moves: [
      { name: "Prediction Thread", energyCost: 1, damage: 50, effect: "Creates a Wikipedia page worth of content" },
      { name: "Network State Vision", energyCost: 3, damage: 90, effect: "Proposes entire new countries" },
      { name: "Bitcoin Bet", energyCost: 2, damage: 70, effect: "Puts money where his mouth is" },
    ],
    stage: "Elite",
    weakness: "Character limits",
    flavor: "Wrote a book about building new countries. Not a metaphor.",
    bangerQuote: "The only person whose 'crazy predictions' thread has its own Wikipedia page.",
    naturalRival: "The existing world order",
    roastBullets: [
      "Tweetstorms that require a PhD to fully understand",
      "Predicted COVID, predicted Bitcoin, predicted... network states?",
      "Every thread is either genius or insane, sometimes both",
      "Built an entire ideology around leaving, but keeps posting",
    ],
  },
  {
    id: "chamath-palihapitiya",
    name: "Chamath Palihapitiya",
    title: "CEO",
    company: "Social Capital",
    imageUrl: "/famous/generated/chamath-palihapitiya-card.png",
    score: 85,
    archetypeName: "The SPAC Attack",
    archetypeEmoji: "💥",
    archetypeDescription: "Disrupted disruption, then disrupted that too",
    element: "chaos",
    moves: [
      { name: "SPAC Launch", energyCost: 2, damage: 60, effect: "Creates instant public company" },
      { name: "Podcast Hot Take", energyCost: 1, damage: 45, effect: "Trends on Twitter immediately" },
      { name: "System Critique", energyCost: 3, damage: 85, effect: "Makes everyone question capitalism" },
    ],
    stage: "Elite",
    weakness: "SPAC performance",
    flavor: "Went from Facebook VP to VC to podcast personality. The triple threat.",
    bangerQuote: "Made billions telling people the system is broken, from inside the system.",
    naturalRival: "His own SPAC investors",
    roastBullets: [
      "The All-In Podcast is just four rich guys agreeing with each other, and we can't stop listening",
      "SPACs went from 'revolutionary' to 'we don't talk about that' real quick",
      "Somehow still the voice of the people despite being a billionaire",
      "Every take is either prescient or catastrophically wrong, no middle ground",
    ],
  },
  {
    id: "david-sacks",
    name: "David Sacks",
    title: "General Partner",
    company: "Craft Ventures",
    imageUrl: "/famous/generated/david-sacks-card.png",
    score: 86,
    archetypeName: "The PayPal Patrician",
    archetypeEmoji: "🏛️",
    archetypeDescription: "Original PayPal Mafia member who never stopped mafiaing",
    element: "politics",
    moves: [
      { name: "PayPal Credential", energyCost: 1, damage: 40, effect: "Establishes immediate authority" },
      { name: "All-In Analysis", energyCost: 2, damage: 65, effect: "Dissects any topic for an hour" },
      { name: "Craft Portfolio", energyCost: 3, damage: 90, effect: "Reveals strategic investments" },
    ],
    stage: "Elite",
    weakness: "Letting things go",
    flavor: "Built the PayPal Mafia, then became the guy who comments on everything.",
    bangerQuote: "PayPal COO turned VC turned podcast pundit. The full Silicon Valley evolution.",
    naturalRival: "Anyone who disagrees on the pod",
    roastBullets: [
      "The 'well actually' energy is strong with this one",
      "All-In Podcast: where four billionaires solve all the world's problems in an hour",
      "Yammer was... something that happened",
      "Has an opinion on everything and will share it, repeatedly",
    ],
  },
  {
    id: "keith-rabois",
    name: "Keith Rabois",
    title: "General Partner",
    company: "Founders Fund",
    imageUrl: "/famous/generated/keith-rabois-card.png",
    score: 87,
    archetypeName: "The Operator Oracle",
    archetypeEmoji: "⚙️",
    archetypeDescription: "Knows how to scale companies because he's done it five times",
    element: "strategy",
    moves: [
      { name: "Operations Audit", energyCost: 2, damage: 70, effect: "Finds every inefficiency" },
      { name: "Scale Playbook", energyCost: 3, damage: 85, effect: "Reveals the secrets of hypergrowth" },
      { name: "Direct Feedback", energyCost: 1, damage: 50, effect: "Tells you exactly what's wrong" },
    ],
    stage: "Elite",
    weakness: "Patience for stupidity",
    flavor: "PayPal, LinkedIn, Square, Opendoor. Just collecting startup logos at this point.",
    bangerQuote: "The only person whose 'how to operate' advice comes with receipts.",
    naturalRival: "Founders who don't listen",
    roastBullets: [
      "Resume reads like a 'greatest hits of Silicon Valley' album",
      "Will tell you exactly what you're doing wrong, whether you asked or not",
      "The 'I've seen this movie before' energy is real because he's starred in it",
      "Tweets like someone who's been right enough times to stop being polite about it",
    ],
  },
  {
    id: "jason-calacanis",
    name: "Jason Calacanis",
    title: "Angel Investor",
    company: "LAUNCH",
    imageUrl: "/famous/generated/jason-calacanis-card.png",
    score: 82,
    archetypeName: "The Hustle Historian",
    archetypeEmoji: "🎤",
    archetypeDescription: "Turned 'knowing everyone' into a legitimate investment strategy",
    element: "politics",
    moves: [
      { name: "Uber Story", energyCost: 1, damage: 35, effect: "Mentions Uber investment (again)" },
      { name: "TWIS Episode", energyCost: 2, damage: 60, effect: "Interviews your competitor" },
      { name: "Angel Network", energyCost: 3, damage: 80, effect: "Activates entire founder community" },
    ],
    stage: "Elite",
    weakness: "Staying quiet",
    flavor: "Early investor in Uber. Will mention it. Frequently.",
    bangerQuote: "The only person who can turn any conversation into an Uber story.",
    naturalRival: "Introverts",
    roastBullets: [
      "If Jason didn't tell you about his Uber investment, did it even happen?",
      "This Week in Startups: 15 years of Jason talking",
      "Angel investing is just networking with money, and he's the final boss",
      "The Uber returns are real, but so is hearing about them forever",
    ],
  },

  // === TIER 2: TECH CEOS ===
  {
    id: "satya-nadella",
    name: "Satya Nadella",
    title: "CEO",
    company: "Microsoft",
    imageUrl: "/famous/generated/satya-nadella-card.png",
    score: 94,
    archetypeName: "The Culture Transformer",
    archetypeEmoji: "☁️",
    archetypeDescription: "Made Microsoft cool again, which nobody thought was possible",
    element: "strategy",
    moves: [
      { name: "Cloud Conquest", energyCost: 3, damage: 95, effect: "Azure takes over another industry" },
      { name: "Growth Mindset", energyCost: 1, damage: 40, effect: "Transforms toxic culture instantly" },
      { name: "OpenAI Alliance", energyCost: 4, damage: 120, effect: "Partners with the competition" },
    ],
    stage: "Legendary",
    weakness: "Bing jokes",
    flavor: "Turned 'developers developers developers' into 'cloud cloud cloud'.",
    bangerQuote: "Inherited Ballmer's Microsoft. Returned a company worth trillions. Humble about it.",
    naturalRival: "Anyone who remembers Windows 8",
    roastBullets: [
      "Made Microsoft likeable. Actual miracle worker.",
      "The 'growth mindset' guy who actually grew Microsoft's market cap by trillions",
      "Copilot is just Clippy with a CS degree",
      "Finally made Bing relevant by putting ChatGPT in it",
    ],
  },
  {
    id: "sundar-pichai",
    name: "Sundar Pichai",
    title: "CEO",
    company: "Google/Alphabet",
    imageUrl: "/famous/generated/sundar-pichai-card.png",
    score: 90,
    archetypeName: "The Careful Captain",
    archetypeEmoji: "🔍",
    archetypeDescription: "Running the world's information, very carefully, with many meetings",
    element: "data",
    moves: [
      { name: "Product Sunset", energyCost: 1, damage: 45, effect: "Kills a beloved Google product" },
      { name: "AI Announcement", energyCost: 2, damage: 70, effect: "Responds to OpenAI, eventually" },
      { name: "Search Monopoly", energyCost: 3, damage: 100, effect: "Maintains 90% market share" },
    ],
    stage: "Legendary",
    weakness: "Moving fast",
    flavor: "Chrome guy became the everything guy. Classic Google promotion.",
    bangerQuote: "Has all the world's information and still can't figure out how to ship products faster than Microsoft.",
    naturalRival: "Product deadlines",
    roastBullets: [
      "Killed more Google products than most people have launched",
      "The 'we're being responsible about AI' guy while Microsoft ships everything",
      "Runs Alphabet like someone who really doesn't want to break anything",
      "Every product launch has 'but we're doing it carefully' energy",
    ],
  },
  {
    id: "jensen-huang",
    name: "Jensen Huang",
    title: "CEO",
    company: "NVIDIA",
    imageUrl: "/famous/generated/jensen-huang-card.png",
    score: 97,
    archetypeName: "The Leather Jacket Visionary",
    archetypeEmoji: "💚",
    archetypeDescription: "Made graphics cards the most important thing in the world, twice",
    element: "vision",
    moves: [
      { name: "GPU Shortage", energyCost: 3, damage: 100, effect: "Makes AI labs beg for hardware" },
      { name: "Kitchen Keynote", energyCost: 1, damage: 50, effect: "Announces trillion-dollar products casually" },
      { name: "CUDA Lock-in", energyCost: 4, damage: 130, effect: "Ensures no one can leave the ecosystem" },
    ],
    stage: "Mythical",
    weakness: "Leather jacket shortage",
    flavor: "Built GPUs for gamers, accidentally powered the AI revolution.",
    bangerQuote: "Started selling graphics cards. Now sells the future. Leather jacket stayed the same.",
    naturalRival: "Anyone with AMD stock",
    roastBullets: [
      "The leather jacket is load-bearing at this point",
      "Made a chip company worth more than most countries' GDP",
      "Every AI company is basically an NVIDIA customer whether they like it or not",
      "Kitchen demos became a whole personality",
    ],
  },
  {
    id: "patrick-collison",
    name: "Patrick Collison",
    title: "CEO",
    company: "Stripe",
    imageUrl: "/famous/generated/patrick-collison-card.png",
    score: 93,
    archetypeName: "The Quiet Powerhouse",
    archetypeEmoji: "📚",
    archetypeDescription: "Built a $95B company while somehow still seeming like a curious student",
    element: "shipping",
    moves: [
      { name: "7 Lines of Code", energyCost: 1, damage: 55, effect: "Simplifies payments forever" },
      { name: "Reading List Drop", energyCost: 2, damage: 65, effect: "Makes everyone feel undereducated" },
      { name: "Infrastructure Play", energyCost: 3, damage: 100, effect: "Quietly becomes essential" },
    ],
    stage: "Legendary",
    weakness: "Unread books",
    flavor: "Built Stripe, then built a library of everything he's read. Which is everything.",
    bangerQuote: "Made payments boring in the best way possible, then made reading cool again.",
    naturalRival: "Anti-intellectualism",
    roastBullets: [
      "Stripe's success is really just delayed book recommendation gratification",
      "The 'I read 200 books a year' guy who built a company worth billions to fund the habit",
      "Makes other founders feel bad about their reading lists",
      "Built critical internet infrastructure, still tweets like a curious nerd",
    ],
  },
  {
    id: "tobi-lutke",
    name: "Tobi Lütke",
    title: "CEO",
    company: "Shopify",
    imageUrl: "/famous/generated/tobi-lutke-card.png",
    score: 89,
    archetypeName: "The Merchant Marine",
    archetypeEmoji: "🛒",
    archetypeDescription: "Built the backbone of internet commerce because Amazon wasn't enough options",
    element: "shipping",
    moves: [
      { name: "Arm the Rebels", energyCost: 2, damage: 70, effect: "Enables million new entrepreneurs" },
      { name: "Ruby Magic", energyCost: 1, damage: 45, effect: "Ships features impossibly fast" },
      { name: "Platform Power", energyCost: 3, damage: 95, effect: "Becomes the anti-Amazon" },
    ],
    stage: "Elite",
    weakness: "Amazon comparisons",
    flavor: "Started a snowboard store, accidentally built an e-commerce empire.",
    bangerQuote: "Made a million entrepreneurs possible while still thinking about snowboards.",
    naturalRival: "Amazon (but politely)",
    roastBullets: [
      "The 'arm the rebels' guy who armed millions of Etsy shops",
      "Proving you can be a nice Canadian and still build a $100B company",
      "Makes Bezos look mean by comparison, which isn't hard",
      "Every small business success story is quietly a Shopify ad",
    ],
  },
  {
    id: "daniel-ek",
    name: "Daniel Ek",
    title: "CEO",
    company: "Spotify",
    imageUrl: "/famous/generated/daniel-ek-card.png",
    score: 84,
    archetypeName: "The Playlist Philosopher",
    archetypeEmoji: "🎵",
    archetypeDescription: "Made all music free, then spent a decade figuring out how to make money from it",
    element: "data",
    moves: [
      { name: "Wrapped Viral", energyCost: 1, damage: 50, effect: "Everyone shares their listening data" },
      { name: "Podcast Pivot", energyCost: 2, damage: 65, effect: "Buys all the podcasters" },
      { name: "Algorithm Playlist", energyCost: 3, damage: 85, effect: "Decides what music you like" },
    ],
    stage: "Elite",
    weakness: "Profitable margins",
    flavor: "Solved music piracy. Created podcast discourse. Mixed results.",
    bangerQuote: "Convinced the world to pay for something they were already stealing, then bought Joe Rogan.",
    naturalRival: "Musicians who want to get paid",
    roastBullets: [
      "Made streaming work by paying artists in exposure and fractions of pennies",
      "The Joe Rogan acquisition was a choice that keeps choosing",
      "Your Wrapped is just a psyop to make you share your data happily",
      "Somehow the most important music company run by someone who never stops apologizing",
    ],
  },
  {
    id: "drew-houston",
    name: "Drew Houston",
    title: "CEO",
    company: "Dropbox",
    imageUrl: "/famous/generated/drew-houston-card.png",
    score: 80,
    archetypeName: "The Sync Sage",
    archetypeEmoji: "📦",
    archetypeDescription: "Made file syncing so reliable we forgot it was ever hard",
    element: "shipping",
    moves: [
      { name: "Jobs Rejection", energyCost: 1, damage: 55, effect: "Uses rejection as motivation" },
      { name: "Sync Magic", energyCost: 2, damage: 65, effect: "Files appear everywhere instantly" },
      { name: "YC Legend", energyCost: 3, damage: 80, effect: "Inspires generations of founders" },
    ],
    stage: "Elite",
    weakness: "Google Drive existing",
    flavor: "Built Dropbox because Steve Jobs told him Apple would crush him. Chose violence.",
    bangerQuote: "Steve Jobs offered to buy him or destroy him. He chose 'no thank you' and built anyway.",
    naturalRival: "Every big tech company's free storage",
    roastBullets: [
      "Said no to Steve Jobs and lived to tell about it",
      "Everyone uses Dropbox until they realize Google Drive is free",
      "Peak YC success story that somehow became the underdog",
      "The 'we were here first' energy in a world that doesn't care",
    ],
  },

  // === TIER 3: AI LEADERS ===
  {
    id: "andrej-karpathy",
    name: "Andrej Karpathy",
    title: "AI Educator",
    company: "Ex-Tesla/OpenAI",
    imageUrl: "/famous/generated/andrej-karpathy-card.png",
    score: 92,
    archetypeName: "The Neural Network Narrator",
    archetypeEmoji: "🧠",
    archetypeDescription: "Makes AI understandable for mortals while building it for gods",
    element: "data",
    moves: [
      { name: "Tutorial Drop", energyCost: 1, damage: 50, effect: "Trains thousands of AI engineers" },
      { name: "GPT Explainer", energyCost: 2, damage: 70, effect: "Makes transformers make sense" },
      { name: "Zero to Hero", energyCost: 3, damage: 95, effect: "Builds neural nets from scratch" },
    ],
    stage: "Legendary",
    weakness: "Tutorial skippers",
    flavor: "Left OpenAI. Left Tesla. Now teaches everyone how to build what he built.",
    bangerQuote: "The only person who makes neural networks feel approachable while casually revolutionizing them.",
    naturalRival: "Paywalled AI education",
    roastBullets: [
      "His YouTube tutorials have trained more AI engineers than most universities",
      "Left the two hottest AI jobs to become an educator. Respect.",
      "The 'let me explain' guy who actually explains it well",
      "Making everyone feel like they could build GPT (they can't, but it feels possible)",
    ],
  },
  {
    id: "yann-lecun",
    name: "Yann LeCun",
    title: "Chief AI Scientist",
    company: "Meta",
    imageUrl: "/famous/generated/yann-lecun-card.png",
    score: 91,
    archetypeName: "The Godfather of Deep Learning",
    archetypeEmoji: "🎓",
    archetypeDescription: "Was building neural networks before it was cool, and won't let you forget it",
    element: "data",
    moves: [
      { name: "Turing Credential", energyCost: 1, damage: 55, effect: "Establishes unquestionable authority" },
      { name: "LLM Correction", energyCost: 2, damage: 70, effect: "Explains why everyone is wrong" },
      { name: "CNN Pioneer", energyCost: 3, damage: 90, effect: "Reminds everyone who invented this" },
    ],
    stage: "Legendary",
    weakness: "LLM hype",
    flavor: "Turing Award winner who spends time arguing with people on Twitter. King energy.",
    bangerQuote: "Won the Turing Award for neural networks, now uses them to post hot takes.",
    naturalRival: "Anyone who overhypes LLMs",
    roastBullets: [
      "Will correct you about AI terminology and he'll be right",
      "The 'actually' guy with the credentials to back it up",
      "Has been right about AI for 40 years and wants you to know it",
      "Facebook pays him to research and argue on Twitter",
    ],
  },
  {
    id: "ilya-sutskever",
    name: "Ilya Sutskever",
    title: "Co-founder",
    company: "SSI",
    imageUrl: "/famous/generated/ilya-sutskever-card.png",
    score: 95,
    archetypeName: "The Safety Sage",
    archetypeEmoji: "🔮",
    archetypeDescription: "Helped build AGI, then got worried about it. Relatable.",
    element: "data",
    moves: [
      { name: "Scaling Insight", energyCost: 2, damage: 80, effect: "Reveals the path to AGI" },
      { name: "Safety Pivot", energyCost: 3, damage: 90, effect: "Changes the entire conversation" },
      { name: "Quiet Genius", energyCost: 1, damage: 50, effect: "Speaks rarely but everyone listens" },
    ],
    stage: "Mythical",
    weakness: "Unsafe AI",
    flavor: "OpenAI co-founder turned safety-focused startup founder. Character development.",
    bangerQuote: "Built the thing everyone's worried about, then became the most worried of all.",
    naturalRival: "Move fast and break things mentality",
    roastBullets: [
      "The 'I've seen things' energy is strong",
      "Left OpenAI to focus on safety, which says something",
      "Rarely tweets but when he does, people pay attention",
      "Might actually be concerned about things the rest of us should be concerned about",
    ],
  },

  // === TIER 4: PRODUCT & GROWTH LEADERS ===
  {
    id: "shreyas-doshi",
    name: "Shreyas Doshi",
    title: "PM Advisor",
    company: "Ex-Stripe/Twitter/Google",
    imageUrl: "/famous/generated/shreyas-doshi-card.png",
    score: 88,
    archetypeName: "The Thread Lord",
    archetypeEmoji: "🧵",
    archetypeDescription: "Turned product management wisdom into an art form, 280 characters at a time",
    element: "strategy",
    moves: [
      { name: "Thread Drop", energyCost: 1, damage: 50, effect: "Spawns a hundred quote tweets" },
      { name: "Framework Deploy", energyCost: 2, damage: 70, effect: "Creates new PM orthodoxy" },
      { name: "LNO Analysis", energyCost: 3, damage: 90, effect: "Explains leverage, neutral, overhead" },
    ],
    stage: "Elite",
    weakness: "Brief answers",
    flavor: "Every PM framework you use probably came from one of his threads.",
    bangerQuote: "Built products at Google, Stripe, Twitter. Now builds the PMs who build products.",
    naturalRival: "People who don't read threads",
    roastBullets: [
      "The thread-to-career-advice pipeline is real and he owns it",
      "Every PM on Twitter is either quoting him or about to",
      "Makes 'actually, there's a framework for that' into a personality",
      "Your favorite PM's favorite PM",
    ],
  },
  {
    id: "julie-zhuo",
    name: "Julie Zhuo",
    title: "Co-founder",
    company: "Sundial",
    imageUrl: "/famous/generated/julie-zhuo-card.png",
    score: 86,
    archetypeName: "The Design Diplomat",
    archetypeEmoji: "🎨",
    archetypeDescription: "Made design management into a discipline people actually respect",
    element: "strategy",
    moves: [
      { name: "Manager Book", energyCost: 2, damage: 70, effect: "Becomes required reading everywhere" },
      { name: "Design Review", energyCost: 1, damage: 45, effect: "Elevates the entire conversation" },
      { name: "Leadership Wisdom", energyCost: 3, damage: 85, effect: "Transforms bad managers into good ones" },
    ],
    stage: "Elite",
    weakness: "Unstructured feedback",
    flavor: "Facebook VP who wrote the book on management. Literally wrote the book.",
    bangerQuote: "Managed the team that designed how billions experience Facebook, then taught everyone else how.",
    naturalRival: "Bad managers",
    roastBullets: [
      "The Making of a Manager is in every new manager's hands whether they know it or not",
      "Made 'design leadership' into an actual career path",
      "Your manager probably read her book and pretended they figured it out themselves",
      "Left Meta to help companies not have bad meetings",
    ],
  },
  {
    id: "andrew-chen",
    name: "Andrew Chen",
    title: "General Partner",
    company: "a16z",
    imageUrl: "/famous/generated/andrew-chen-card.png",
    score: 87,
    archetypeName: "The Growth Guru",
    archetypeEmoji: "📈",
    archetypeDescription: "Documented every growth hack before 'growth hack' was cringe",
    element: "data",
    moves: [
      { name: "Essay Archive", energyCost: 1, damage: 50, effect: "Blog posts from 2012 still relevant" },
      { name: "Network Effect", energyCost: 2, damage: 75, effect: "Explains why your startup won't work" },
      { name: "Growth Thesis", energyCost: 3, damage: 90, effect: "Identifies the next viral product" },
    ],
    stage: "Elite",
    weakness: "Unscalable tactics",
    flavor: "Uber growth lead turned a16z partner. The natural evolution of a growth person.",
    bangerQuote: "Wrote the essays that launched a thousand growth teams, then funded the best ones.",
    naturalRival: "Vanity metrics",
    roastBullets: [
      "His blog posts from 2012 are still getting passed around in Slack channels",
      "Proved that the best way to grow is to write about growth",
      "Every growth PM has his essays bookmarked whether they admit it or not",
      "Turned documenting growth into a growth strategy itself",
    ],
  },

  // === TIER 5: INDIE HACKERS & BUILDERS ===
  {
    id: "pieter-levels",
    name: "Pieter Levels",
    title: "Indie Hacker",
    company: "Nomad List / Photo AI",
    imageUrl: "/famous/generated/pieter-levels-card.png",
    score: 90,
    archetypeName: "The Solo Shipper Supreme",
    archetypeEmoji: "🚀",
    archetypeDescription: "Makes millions alone while tweeting the entire journey",
    element: "shipping",
    moves: [
      { name: "Ship It Now", energyCost: 1, damage: 55, effect: "Launches product in hours" },
      { name: "MRR Tweet", energyCost: 2, damage: 70, effect: "Makes funded founders jealous" },
      { name: "12 Startups", energyCost: 3, damage: 95, effect: "Launches one startup per month" },
    ],
    stage: "Legendary",
    weakness: "Team coordination",
    flavor: "12 startups in 12 months. Some actually worked. That's the game.",
    bangerQuote: "Built more profitable businesses solo than most teams do with millions in funding.",
    naturalRival: "VCs who don't get bootstrapping",
    roastBullets: [
      "The 'just ship it' guy who actually just ships it, repeatedly",
      "Making VC-backed founders feel inadequate since 2014",
      "Tweets his MRR like it's a sport and he's winning",
      "Proving that the best startup advice is 'be Pieter Levels'",
    ],
  },
  {
    id: "sahil-lavingia",
    name: "Sahil Lavingia",
    title: "CEO",
    company: "Gumroad",
    imageUrl: "/famous/generated/sahil-lavingia-card.png",
    score: 85,
    archetypeName: "The Minimalist Mogul",
    archetypeEmoji: "🎯",
    archetypeDescription: "Built, lost, and rebuilt a company while documenting every lesson",
    element: "shipping",
    moves: [
      { name: "Transparency Post", energyCost: 1, damage: 50, effect: "Shares all the numbers publicly" },
      { name: "Creator Economy", energyCost: 2, damage: 70, effect: "Enables millions to sell online" },
      { name: "Minimalist Pivot", energyCost: 3, damage: 85, effect: "Proves less is more" },
    ],
    stage: "Elite",
    weakness: "Overcomplicating things",
    flavor: "Raised $8M, returned it, made it work anyway. That's a flex.",
    bangerQuote: "Turned a 'failed' startup into a profitable business and a bestselling book about it.",
    naturalRival: "Growth at all costs mentality",
    roastBullets: [
      "The 'Minimalist Entrepreneur' who maximized transparency",
      "Made failing forward into an actual business strategy",
      "Every tweet is either wisdom or a painting",
      "Proved that you can succeed by publicly failing first",
    ],
  },
  {
    id: "guillermo-rauch",
    name: "Guillermo Rauch",
    title: "CEO",
    company: "Vercel",
    imageUrl: "/famous/generated/guillermo-rauch-card.png",
    score: 91,
    archetypeName: "The Framework Forger",
    archetypeEmoji: "▲",
    archetypeDescription: "Made deploying websites so easy that everyone forgot it was ever hard",
    element: "shipping",
    moves: [
      { name: "Next.js Drop", energyCost: 2, damage: 75, effect: "Changes frontend development forever" },
      { name: "Deploy Preview", energyCost: 1, damage: 50, effect: "Every PR gets a live URL" },
      { name: "Edge Function", energyCost: 3, damage: 95, effect: "Code runs everywhere instantly" },
    ],
    stage: "Legendary",
    weakness: "Self-hosting advocates",
    flavor: "Built Next.js, then built a company to host it. Vertical integration energy.",
    bangerQuote: "Created the framework, created the deployment platform, created the ecosystem. Any questions?",
    naturalRival: "People who think Vercel is too expensive",
    roastBullets: [
      "The triangle logo became a personality",
      "Made every frontend developer a deploy button away from production",
      "Ship ship ship is not just a motto, it's a business model",
      "Next.js is free, deploying it is where they get you",
    ],
  },

  // === TIER 6: CONTENT CREATORS & MEDIA ===
  {
    id: "theo-browne",
    name: "Theo Browne",
    title: "CEO",
    company: "Ping Labs",
    imageUrl: "/famous/generated/theo-browne-card.png",
    score: 83,
    archetypeName: "The TypeScript Tornado",
    archetypeEmoji: "🌪️",
    archetypeDescription: "Turned strong opinions about JavaScript into a media empire",
    element: "chaos",
    moves: [
      { name: "Hot Take", energyCost: 1, damage: 50, effect: "Trends immediately" },
      { name: "T3 Stack", energyCost: 2, damage: 70, effect: "Defines the meta for a generation" },
      { name: "Stream Roast", energyCost: 3, damage: 85, effect: "Live codes while dunking on bad takes" },
    ],
    stage: "Elite",
    weakness: "Not having an opinion",
    flavor: "React influencer who became a React influencer influencer.",
    bangerQuote: "Made TypeScript discourse into content and content into a career.",
    naturalRival: "JavaScript without types",
    roastBullets: [
      "Every hot take is either brilliant or bait (often both)",
      "T3 stack became a thing because he willed it into existence",
      "Screaming about code on YouTube as a legitimate career path",
      "The 'let me explain why you're wrong about React' guy",
    ],
  },
  {
    id: "primeagen",
    name: "ThePrimeagen",
    title: "Content Creator",
    company: "Ex-Netflix",
    imageUrl: "/famous/generated/primeagen-card.png",
    score: 82,
    archetypeName: "The Vim Virtuoso",
    archetypeEmoji: "⌨️",
    archetypeDescription: "Left Netflix to yell about Vim and somehow made it work",
    element: "chaos",
    moves: [
      { name: "Vim Flex", energyCost: 1, damage: 50, effect: "Navigates faster than you can see" },
      { name: "FAANG Roast", energyCost: 2, damage: 70, effect: "Explains why big tech is broken" },
      { name: "Stream Rant", energyCost: 3, damage: 85, effect: "Entertains while educating" },
    ],
    stage: "Elite",
    weakness: "Using a mouse",
    flavor: "The only person who can make text editor choices entertaining.",
    bangerQuote: "Proved that being extremely online about developer tools is a viable career.",
    naturalRival: "VS Code fans",
    roastBullets: [
      "Made 'btw I use vim' into actual content",
      "Twitch streaming but make it about terminal efficiency",
      "Left a FAANG job to argue about text editors. Living the dream.",
      "The most entertaining person to ever care about keyboard shortcuts",
    ],
  },
  {
    id: "kara-swisher",
    name: "Kara Swisher",
    title: "Tech Journalist",
    company: "Pivot Podcast",
    imageUrl: "/famous/generated/kara-swisher-card.png",
    score: 88,
    archetypeName: "The Tech Interrogator",
    archetypeEmoji: "🎙️",
    archetypeDescription: "Made tech CEOs uncomfortable before it was popular",
    element: "politics",
    moves: [
      { name: "Hard Question", energyCost: 1, damage: 55, effect: "CEO starts sweating" },
      { name: "Pivot Take", energyCost: 2, damage: 70, effect: "Sets the week's tech narrative" },
      { name: "Industry Expose", energyCost: 3, damage: 95, effect: "Reveals what everyone was thinking" },
    ],
    stage: "Elite",
    weakness: "Podcast dodgers",
    flavor: "Asking the questions everyone's thinking but no one else will ask.",
    bangerQuote: "Been calling out tech nonsense since before most people knew tech was nonsense.",
    naturalRival: "PR teams",
    roastBullets: [
      "The only journalist tech CEOs are scared of",
      "Pivot podcast: where Scott Galloway agrees with Kara for an hour",
      "Has been right about everything wrong with tech for decades",
      "Interviews feel like depositions and we're here for it",
    ],
  },
  {
    id: "ben-thompson",
    name: "Ben Thompson",
    title: "Founder",
    company: "Stratechery",
    imageUrl: "/famous/generated/ben-thompson-card.png",
    score: 89,
    archetypeName: "The Aggregation Analyst",
    archetypeEmoji: "📊",
    archetypeDescription: "Turned explaining business strategy into the business strategy",
    element: "strategy",
    moves: [
      { name: "Daily Update", energyCost: 1, damage: 50, effect: "Sets the industry conversation" },
      { name: "Aggregation Theory", energyCost: 2, damage: 75, effect: "Explains every platform business" },
      { name: "Deep Analysis", energyCost: 3, damage: 95, effect: "5000 words of pure insight" },
    ],
    stage: "Elite",
    weakness: "Writing short articles",
    flavor: "Made people pay for newsletters before it was a whole thing.",
    bangerQuote: "Invented the tech newsletter business model and gave everyone the strategy to understand it.",
    naturalRival: "Free content",
    roastBullets: [
      "Every tech executive reads Stratechery and pretends they don't",
      "Aggregation Theory explains everything, according to him",
      "Made 'it's all about the demand side' into a whole career",
      "The OG of 'you should pay for this newsletter'",
    ],
  },

  // === TIER 7: CRYPTO & WEB3 ===
  {
    id: "vitalik-buterin",
    name: "Vitalik Buterin",
    title: "Co-founder",
    company: "Ethereum",
    imageUrl: "/famous/generated/vitalik-buterin-card.png",
    score: 94,
    archetypeName: "The Proof-of-Stake Prophet",
    archetypeEmoji: "💎",
    archetypeDescription: "Built a world computer and still lives like a grad student",
    element: "vision",
    moves: [
      { name: "Whitepaper Drop", energyCost: 2, damage: 80, effect: "Creates entire new economy" },
      { name: "Technical Thread", energyCost: 1, damage: 50, effect: "Only 10% of crypto understands" },
      { name: "Merge Complete", energyCost: 4, damage: 120, effect: "Changes how blockchain works" },
    ],
    stage: "Legendary",
    weakness: "Formal attire",
    flavor: "Created Ethereum, wears the same shirt, has thoughts about everything.",
    bangerQuote: "Made a blockchain that actually does stuff and never let the money change him.",
    naturalRival: "Bitcoin maximalists",
    roastBullets: [
      "Worth billions, still looks like he's borrowing clothes",
      "Every tweet is either genius or an alien trying to relate to humans",
      "Built the foundation for a trillion-dollar ecosystem in his early 20s",
      "The only crypto founder who seems genuinely confused by his own wealth",
    ],
  },
  {
    id: "brian-armstrong",
    name: "Brian Armstrong",
    title: "CEO",
    company: "Coinbase",
    imageUrl: "/famous/generated/brian-armstrong-card.png",
    score: 86,
    archetypeName: "The Compliance Cowboy",
    archetypeEmoji: "🤠",
    archetypeDescription: "Made crypto respectable by fighting the SEC instead of ignoring them",
    element: "shipping",
    moves: [
      { name: "SEC Battle", energyCost: 2, damage: 70, effect: "Fights regulators publicly" },
      { name: "IPO Achievement", energyCost: 3, damage: 90, effect: "First major crypto public company" },
      { name: "Policy Tweet", energyCost: 1, damage: 45, effect: "Shapes crypto regulation debate" },
    ],
    stage: "Elite",
    weakness: "SEC meetings",
    flavor: "Built the crypto on-ramp while regulators tried to close the road.",
    bangerQuote: "Made buying crypto as easy as buying stocks, then fought to keep it that way.",
    naturalRival: "Gary Gensler",
    roastBullets: [
      "The crypto CEO who actually talks to regulators (by suing them)",
      "Made 'regulatory clarity' sound exciting somehow",
      "Every tweet about policy is a subtle middle finger to the SEC",
      "Running a crypto exchange in America is a contact sport",
    ],
  },

  // === TIER 8: MORE ICONIC FOUNDERS ===
  {
    id: "stewart-butterfield",
    name: "Stewart Butterfield",
    title: "Co-founder",
    company: "Slack (now Salesforce)",
    imageUrl: "/famous/generated/stewart-butterfield-card.png",
    score: 87,
    archetypeName: "The Pivot Perfectionist",
    archetypeEmoji: "💬",
    archetypeDescription: "Failed at games twice, accidentally built two massive companies",
    element: "vision",
    moves: [
      { name: "Pivot Magic", energyCost: 2, damage: 75, effect: "Failure becomes billion-dollar success" },
      { name: "Workplace Chat", energyCost: 1, damage: 50, effect: "Changes how teams communicate" },
      { name: "Exit Strategy", energyCost: 3, damage: 90, effect: "Sells to enterprise giant" },
    ],
    stage: "Elite",
    weakness: "Game development apparently",
    flavor: "Flickr came from a failed game. Slack came from a failed game. Keep failing, Stewart.",
    bangerQuote: "The greatest accidental product genius in tech history.",
    naturalRival: "Email (and Microsoft Teams)",
    roastBullets: [
      "Two failed games, two billion-dollar pivots. The math maths.",
      "Made workplace chat cool and addictive, for better or worse",
      "Your company's Slack addiction is his retirement fund",
      "Sold to Salesforce and now tweets philosophy. Living the dream.",
    ],
  },
  {
    id: "aaron-levie",
    name: "Aaron Levie",
    title: "CEO",
    company: "Box",
    imageUrl: "/famous/generated/aaron-levie-card.png",
    score: 81,
    archetypeName: "The Enterprise Entertainer",
    archetypeEmoji: "📦",
    archetypeDescription: "Made enterprise software and Twitter both his full-time job",
    element: "politics",
    moves: [
      { name: "Tweet Storm", energyCost: 1, damage: 45, effect: "Most entertaining CEO on Twitter" },
      { name: "Enterprise Pitch", energyCost: 2, damage: 65, effect: "Makes B2B sound exciting" },
      { name: "AI Pivot", energyCost: 3, damage: 80, effect: "Repositions for the AI era" },
    ],
    stage: "Elite",
    weakness: "Not tweeting",
    flavor: "CEO who tweets more than some social media managers.",
    bangerQuote: "Built an enterprise company while maintaining the best Twitter presence of any CEO.",
    naturalRival: "Dropbox (forever)",
    roastBullets: [
      "The only enterprise CEO who's genuinely funny on Twitter",
      "Box vs Dropbox discourse has been going since the Obama administration",
      "Tweets like someone who's procrastinating from enterprise sales calls",
      "Made 'secure cloud storage' somehow entertaining",
    ],
  },
  {
    id: "jason-fried",
    name: "Jason Fried",
    title: "CEO",
    company: "37signals",
    imageUrl: "/famous/generated/jason-fried-card.png",
    score: 84,
    archetypeName: "The Anti-Hustle Hustler",
    archetypeEmoji: "⏰",
    archetypeDescription: "Made 'work less, charge more' into a whole philosophy",
    element: "vision",
    moves: [
      { name: "Rework Wisdom", energyCost: 1, damage: 50, effect: "Contradicts all startup advice" },
      { name: "Calm Company", energyCost: 2, damage: 70, effect: "Proves profitability > growth" },
      { name: "VC Rejection", energyCost: 3, damage: 85, effect: "Bootstrapped and proud" },
    ],
    stage: "Elite",
    weakness: "Venture capital mentality",
    flavor: "Wrote books about not overworking while clearly working on writing books about not overworking.",
    bangerQuote: "Built a profitable company by telling everyone else how to build profitable companies.",
    naturalRival: "Hustle culture influencers",
    roastBullets: [
      "The 'actually, you don't need to work 80 hours' guy who tweets 80 times a week",
      "Basecamp is cool but the real product is contrarian business advice",
      "Rework is in every founder's bookshelf whether they follow it or not",
      "Made 'anti-growth' into a growth strategy",
    ],
  },
  {
    id: "dhh",
    name: "David Heinemeier Hansson",
    title: "CTO",
    company: "37signals",
    imageUrl: "/famous/generated/dhh-card.png",
    score: 86,
    archetypeName: "The Framework Firebrand",
    archetypeEmoji: "💎",
    archetypeDescription: "Created Ruby on Rails, then created discourse about everything else",
    element: "chaos",
    moves: [
      { name: "Rails Release", energyCost: 2, damage: 75, effect: "Shapes web development again" },
      { name: "Cloud Exit", energyCost: 3, damage: 90, effect: "Proves you don't need AWS" },
      { name: "Hot Take", energyCost: 1, damage: 55, effect: "Starts a Twitter war" },
    ],
    stage: "Elite",
    weakness: "Not having strong opinions",
    flavor: "Built a framework that shaped web development, tweets like someone who has time.",
    bangerQuote: "Made web development accessible, then made everyone argue about everything.",
    naturalRival: "TypeScript fans, VC culture, car restraints",
    roastBullets: [
      "Ruby on Rails changed the world. His tweets try to change it again daily.",
      "The 'well actually' energy combined with 'I created Rails' energy is powerful",
      "Simultaneously a legendary developer and a legendary hot take machine",
      "Owns a racecar and has opinions about everything, especially cloud computing",
    ],
  },
  {
    id: "dharmesh-shah",
    name: "Dharmesh Shah",
    title: "CTO & Co-founder",
    company: "HubSpot",
    imageUrl: "/famous/generated/dharmesh-shah-card.png",
    score: 83,
    archetypeName: "The Inbound Inventor",
    archetypeEmoji: "🧲",
    archetypeDescription: "Made marketing software and culture codes before either was cool",
    element: "data",
    moves: [
      { name: "Culture Code", energyCost: 2, damage: 70, effect: "Defines company values industry-wide" },
      { name: "Inbound Strategy", energyCost: 1, damage: 50, effect: "Proves content > cold calls" },
      { name: "Domain Collector", energyCost: 3, damage: 80, effect: "Owns more domains than countries" },
    ],
    stage: "Elite",
    weakness: "Outbound marketing",
    flavor: "Built HubSpot, writes about culture, buys domain names. Busy guy.",
    bangerQuote: "Created inbound marketing, which is ironic because his tweets are everywhere.",
    naturalRival: "Cold emailers",
    roastBullets: [
      "The Culture Code doc is required reading at companies that want to seem progressive",
      "Owns more domains than some countries have websites",
      "Made marketing nerds feel like they're doing something meaningful",
      "HubSpot Academy has trained more marketers than traditional marketing degrees",
    ],
  },
  {
    id: "fei-fei-li",
    name: "Fei-Fei Li",
    title: "Professor",
    company: "Stanford AI Lab",
    imageUrl: "/famous/generated/fei-fei-li-card.png",
    score: 93,
    archetypeName: "The ImageNet Illuminator",
    archetypeEmoji: "👁️",
    archetypeDescription: "Taught AI to see by showing it millions of labeled pictures",
    element: "data",
    moves: [
      { name: "ImageNet Legacy", energyCost: 2, damage: 85, effect: "Enabled entire computer vision industry" },
      { name: "Ethics Advocate", energyCost: 1, damage: 50, effect: "Pushes for human-centered AI" },
      { name: "Research Breakthrough", energyCost: 3, damage: 100, effect: "Advances the field again" },
    ],
    stage: "Legendary",
    weakness: "AI without ethics",
    flavor: "Created the dataset that launched the deep learning revolution. No big deal.",
    bangerQuote: "ImageNet made modern AI possible. The world barely said thank you.",
    naturalRival: "AI without human-centered values",
    roastBullets: [
      "Every AI that recognizes images probably trained on her dataset",
      "Quietly enabled the entire computer vision industry",
      "More impact than most tech CEOs, less Twitter presence",
      "Human-centered AI advocate in a move-fast-break-things industry",
    ],
  },
  {
    id: "casey-newton",
    name: "Casey Newton",
    title: "Editor",
    company: "Platformer",
    imageUrl: "/famous/generated/casey-newton-card.png",
    score: 81,
    archetypeName: "The Platform Prosecutor",
    archetypeEmoji: "⚖️",
    archetypeDescription: "Writes about social media problems while being really good at social media",
    element: "politics",
    moves: [
      { name: "Newsletter Drop", energyCost: 1, damage: 50, effect: "Required reading for tech workers" },
      { name: "Platform Expose", energyCost: 2, damage: 70, effect: "Reveals what platforms hide" },
      { name: "Trust & Safety Deep Dive", energyCost: 3, damage: 85, effect: "Explains content moderation" },
    ],
    stage: "Elite",
    weakness: "Platforms that behave",
    flavor: "Left The Verge to build Platformer. The content moderation beat found him.",
    bangerQuote: "Made content moderation coverage into must-read journalism.",
    naturalRival: "Trust & Safety teams (and their critics)",
    roastBullets: [
      "The 'what did the platforms do this week' guy we all rely on",
      "Substack success story who still covers Substack critically",
      "Every platform controversy eventually becomes a Platformer edition",
      "Independent journalist voice in a sea of access journalism",
    ],
  },
  {
    id: "packy-mccormick",
    name: "Packy McCormick",
    title: "Founder",
    company: "Not Boring",
    imageUrl: "/famous/generated/packy-mccormick-card.png",
    score: 84,
    archetypeName: "The Optimism Optimizer",
    archetypeEmoji: "🚀",
    archetypeDescription: "Made long-form business analysis exciting, which shouldn't be possible",
    element: "vision",
    moves: [
      { name: "Long Read", energyCost: 2, damage: 70, effect: "10,000 words that fly by" },
      { name: "Company Profile", energyCost: 1, damage: 50, effect: "Makes any company sound exciting" },
      { name: "Optimism Injection", energyCost: 3, damage: 85, effect: "Turns cynics into believers" },
    ],
    stage: "Elite",
    weakness: "Pessimism",
    flavor: "Writes 10,000 word essays about companies and people actually read them.",
    bangerQuote: "Turned 'this company is interesting' into a genre of content.",
    naturalRival: "Cynical tech coverage",
    roastBullets: [
      "Not Boring is boring's opposite and somehow that works",
      "Makes you optimistic about companies you'll never invest in",
      "Every essay is too long and somehow not long enough",
      "The bullish case for everything, professionally",
    ],
  },
  {
    id: "dan-abramov",
    name: "Dan Abramov",
    title: "Engineer",
    company: "Ex-Meta",
    imageUrl: "/famous/generated/dan-abramov-card.png",
    score: 88,
    archetypeName: "The Redux Revolutionary",
    archetypeEmoji: "⚛️",
    archetypeDescription: "Changed how people write JavaScript by making state management somewhat understandable",
    element: "shipping",
    moves: [
      { name: "Redux Release", energyCost: 2, damage: 75, effect: "Standardizes state management" },
      { name: "Patient Explanation", energyCost: 1, damage: 45, effect: "Makes complex concepts clear" },
      { name: "React Insight", energyCost: 3, damage: 90, effect: "Reveals how React really works" },
    ],
    stage: "Elite",
    weakness: "People misusing Redux",
    flavor: "Created Redux, joined React team, explains things patiently while the internet argues.",
    bangerQuote: "Made state management a conversation topic at parties (developer parties).",
    naturalRival: "People who think they understand React better than him",
    roastBullets: [
      "Redux is in half the apps on the internet, for better or worse",
      "Joined React team and made hooks happen",
      "The most patient explainer in a community that loves to argue",
      "Left Meta and somehow people cared about a library maintainer leaving",
    ],
  },
  {
    id: "kent-c-dodds",
    name: "Kent C. Dodds",
    title: "Educator",
    company: "EpicWeb.dev",
    imageUrl: "/famous/generated/kent-c-dodds-card.png",
    score: 82,
    archetypeName: "The Testing Evangelist",
    archetypeEmoji: "✅",
    archetypeDescription: "Made people actually want to write tests, which is a miracle",
    element: "shipping",
    moves: [
      { name: "Testing Library", energyCost: 2, damage: 70, effect: "Changes how everyone tests" },
      { name: "Course Launch", energyCost: 1, damage: 50, effect: "Educates thousands instantly" },
      { name: "Best Practices", energyCost: 3, damage: 85, effect: "Establishes new standards" },
    ],
    stage: "Elite",
    weakness: "Untested code",
    flavor: "Built an education empire by teaching people to write tests they were avoiding.",
    bangerQuote: "Convinced developers to write tests. Actual sorcery.",
    naturalRival: "People who skip testing",
    roastBullets: [
      "Testing Trophy > Testing Pyramid and he will die on this hill",
      "Made React Testing Library the standard by being persistently right",
      "Every course makes you feel bad about your testing practices",
      "The wholesome energy in a cynical industry",
    ],
  },
  {
    id: "emad-mostaque",
    name: "Emad Mostaque",
    title: "Founder",
    company: "Stability AI",
    imageUrl: "/famous/generated/emad-mostaque-card.png",
    score: 79,
    archetypeName: "The Open Source Oracle",
    archetypeEmoji: "🖼️",
    archetypeDescription: "Released Stable Diffusion and changed everything, including his job status",
    element: "chaos",
    moves: [
      { name: "Open Release", energyCost: 2, damage: 75, effect: "Democratizes AI instantly" },
      { name: "Chaos Factor", energyCost: 1, damage: 50, effect: "Disrupts entire industries" },
      { name: "Model Drop", energyCost: 3, damage: 85, effect: "Releases what others gatekeep" },
    ],
    stage: "Senior",
    weakness: "Board management",
    flavor: "Made AI image generation accessible to everyone. Chaos ensued.",
    bangerQuote: "Democratized AI art generation and let the internet figure out the implications.",
    naturalRival: "Closed AI labs",
    roastBullets: [
      "Stable Diffusion changed the internet and then he left the company",
      "Open source AI hero or chaos agent, depending on who you ask",
      "Promised to open source everything, delivered on that at least",
      "The 'release it and see what happens' philosophy personified",
    ],
  },
];

// Get a random card for showcase
export function getRandomFamousCard(): FamousCard {
  return FAMOUS_CARDS[Math.floor(Math.random() * FAMOUS_CARDS.length)];
}

// Get card by ID
export function getFamousCardById(id: string): FamousCard | undefined {
  return FAMOUS_CARDS.find(card => card.id === id);
}

// Search famous cards by name (case-insensitive fuzzy match)
export function searchFamousCards(query: string): FamousCard[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return [];

  return FAMOUS_CARDS.filter(card => {
    const name = card.name.toLowerCase();
    const company = card.company.toLowerCase();
    // Match by name or company
    return name.includes(normalizedQuery) || company.includes(normalizedQuery);
  }).slice(0, 5); // Return top 5 matches
}

// Get famous card by exact name match (case-insensitive)
export function getFamousCardByName(name: string): FamousCard | undefined {
  const normalizedName = name.toLowerCase().trim();
  return FAMOUS_CARDS.find(card => card.name.toLowerCase() === normalizedName);
}
